### ISSUE TITLE
jenkins-plugin-cli does not use http_proxy/https_proxy environment variables

### ISSUE THREAD

**Issue by gutschet** [jenkinsci/docker#1005]
Hi,

I am building own jenkins images with preinstalled plugins. In my Dockerfile, I used to execute the install-plugins.sh shellscript like this:
```
COPY ./plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
```

This works perfectly, but since some weeks, I warns me because of deprecation:
```
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
```

This is why I wanted to switch to jenkins-plugin-cli today, so I changed my Dockerfile:
```
COPY ./plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --verbose -f /usr/share/jenkins/ref/plugins.txt
```

But it does not work, but throws the following error:
```File containing list of plugins to be downloaded: /usr/share/jenkins/ref/plugins.txt
Reading in plugins from /usr/share/jenkins/ref/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war
Jenkins version: 2.263

Retrieving update center information
Created cache at: /root/.cache/jenkins-plugin-management-cli
Cache miss for: update-center-2.263
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:573)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:592)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:113)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2795)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:567)
        ... 4 more
Error getting update center json
```

I do not see any requests go to my proxy, so I guess that the jenkins-plugin-cli simply does not care about my http_proxy/https_proxy environment variables (which are used by the old, deprecated script). 

Do I have to configure the proxy in another way for the jenkins-plugin-cli?
I checked `jenkins-plugin-cli --help` but there is no option to set a proxy.

Kind regards
Timo

**Comment by gutschet** [comment]
Hi,

I found the following in the documentation from the plugin-installation-manager:
https://github.com/jenkinsci/plugin-installation-manager-tool#proxy-support

But how do I do this when using jenkins-plugin-cli in a docker file?

Kind regards (and sorry for the stupid question)
Timo

**Comment by jansohn** [comment]
You cannot use the script but need to run the `java` command directly like this:

     java -Dhttps.proxyHost=${HTTP_PROXY_HOST} -Dhttps.proxyPort=${HTTP_PROXY_PORT} -jar /usr/lib/jenkins-plugin-manager.jar -f /usr/share/jenkins/ref/plugins.txt

And yes, I also don't like the current behavior...

**Comment by slide** [comment]
Since this is an issue with the plugin-installation-manager-tool, I'm going to close this out.

**Comment by dolevhadad** [comment]
service docker restart solved the problem.

**Comment by abdennour** [comment]
I ran it with verbose:

```sh
jenkins-plugin-cli --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt" --verbose
```
I concluded that i need to set some env vars . i did : 

```sh
export JENKINS_UC=http://nexus.cicd/repository/updates.jenkins.io/update-center.json
export JENKINS_UC_EXPERIMENTAL=http://nexus.cicd/repository/updates.jenkins.io/experimental/update-center.json
export JENKINS_PLUGIN_INFO=http://nexus.cicd/repository/updates.jenkins.io/plugin-versions.json
export JENKINS_INCREMENTALS_REPO_MIRROR=http://nexus.cicd/repository/repo.jenkins-ci.org/incrementals
```

Agree or disagree! but it works with me.
In helm release, just add these env vars for the init container in initContainers

**Comment by mrgasco** [comment]
You can set an extra environment variable
- name: JAVA_OPTS
   value: "-Dhttp.proxyHost=myproxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=myproxy -Dhttps.proxyPort=3128"

**Comment by YannikSue** [comment]
For me worked following:
- declare ARG _JAVA_OPTIONS inside of your dockerfile 
- pass "-Dhttps.proxyHost=myproxy -Dhttps.proxyPort=myport" as --build-arg
I could see that the jenkins-plugin-cli picked up the _JAVA_OPTIONS.  This way you can set your proxy only during the build phase, which might be helpful for others, too.
