### ISSUE TITLE
Problem starting the ssh daemon service

### ISSUE THREAD

**Issue by ceme393** [jenkinsci/docker#1076]
I am trying to start up two two Jenkins instances in two docker containers and enable ssh to be able to make one the slave of another.

I use the following command to start the container

docker run --name myJenkins2 -p 8081:8080 -p 50001:50000 jenkins/jenkins:lts

Once logged into jenkins and via Manage Jenkins and Configure Global Security, i try to enable SSH server on port 22. It fails and i get the following in the container logs:

2021-02-12 13:08:39.314+0000 [id=52]    SEVERE  o.j.main.modules.sshd.SSHD#restart: Failed to restart SSHD
java.net.SocketException: Permission denied
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:163)
        at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:63)
        at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:87)
        at org.apache.sshd.server.SshServer.start(SshServer.java:332)
        at org.jenkinsci.main.modules.sshd.SSHD.start(SSHD.java:177)
        at org.jenkinsci.main.modules.sshd.SSHD.restart(SSHD.java:232)
        at org.jenkinsci.main.modules.sshd.SSHD$1.run(SSHD.java:114)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Does someone know if starting SSH server is possible with this docker images of Jenkins? If there is another way to setup connection between several such jenkins, kindly share.

**Comment by slide** [comment]
Please use the users mailing list for asking questions. https://groups.google.com/g/jenkinsci-users
