### ISSUE TITLE
Install plugins? Not a ZIP archive

### ISSUE THREAD

**Issue by WillBeebe** [jenkinsci/docker#109]
Hey guys!

I'm having issues installing a plugin. I copied plugins.sh to my local computer and ran that in my plugins.txt and that worked just fine. But in my docker container I can't seem to get it working. Le tme know if there's any other info I can provide!

here's my Dockerfile
```
FROM jenkins                                                                   
                                                                              
COPY plugins.txt /usr/share/jenkins/plugins.txt            
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt 
```
and plugins.txt
```
scm-sync-configuration
```

I'm getting this error:
```
Jun 03, 2015 7:55:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Inspecting plugin /var/jenkins_home/plugins/scm-sync-configuration.hpi
java.io.IOException: Failed to expand /var/jenkins_home/plugins/scm-sync-configuration.hpi
	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:513)
	at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:164)
	at hudson.PluginManager$1$3$1.run(PluginManager.java:253)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:903)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Error while expanding /var/jenkins_home/plugins/scm-sync-configuration.hpi
java.util.zip.ZipException: archive is not a ZIP archive
	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:192)
	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
	at hudson.ClassicPluginStrategy.unzipExceptClasses(ClassicPluginStrategy.java:585)
	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:510)
	... 10 more
Caused by: java.util.zip.ZipException: archive is not a ZIP archive
	at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:481)
	at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:320)
	at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:186)
	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:170)
	... 13 more
```

**Comment by WillBeebe** [comment]
I poked around inside the container a bit
```
docker exec -it [container-id] bash
file /var/jenkins_home/plugins/scm-sync-configuration.hpi
scm-sync-configuration.hpi: HTML document, ASCII text
```

the contents are:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /plugins/scm-sync-configuration//scm-sync-configuration.hpi was not found on this server.</p>
<hr>
<address>Apache/2.2.14 (Ubuntu) Server at mirrors.jenkins-ci.org Port 80</address>
</body></html>
```

**Comment by WillBeebe** [comment]
Figured out a solution! That url has a double-slash in it where I'm guessing the version goes. Changing my plugins.txt to:
```
scm-sync-configuration:latest
```

Fixed the issue.
