### ISSUE TITLE
issue with jenkins/jenkins:lts

### ISSUE THREAD

**Issue by danseo-reisys** [jenkinsci/docker#1098]
### Version report

Jenkins and plugins versions report:

```
Copy/paste here....
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Azure Kubernetes 
```

### Reproduction steps

After jenkins/jenkins:LTS was updated, jenkins instance on our AKS crashed and can not startup.

2021-03-29 18:03:59.219+0000 [id=40]    SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Simple disk usage computation [#1]/40) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
        at jenkins.model.Jenkins.get(Jenkins.java:775)
        at hudson.Plugin.getConfigXml(Plugin.java:296)
        at hudson.Plugin.save(Plugin.java:280)
        at com.cloudbees.simplediskusage.QuickDiskUsagePlugin$2.run(QuickDiskUsagePlugin.java:267)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
### Results

Expected result:

jenkins container starting up no problem
Actual result:

Events:
  Type     Reason     Age                     From                                        Message
  ----     ------     ----                    ----                                        -------
  Normal   Pulling    23m (x24 over 118m)     kubelet, aks-nodepool2-35434671-vmss000000  Pulling image "jenkins/jenkins:lts"
  Warning  BackOff    8m55s (x241 over 103m)  kubelet, aks-nodepool2-35434671-vmss000000  Back-off restarting failed container
  Warning  Unhealthy  3m27s (x203 over 117m)  kubelet, aks-nodepool2-35434671-vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 500

**Comment by MarkEWaite** [comment]
The issue tracker is used to track issues with the Jenkins Docker image.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
