### ISSUE TITLE
Jenkins CLI fails

### ISSUE THREAD

**Issue by anthonygreen** [jenkinsci/docker#116]
Jenkins CLI fails against the container

    wget http://localhost:8080/ 

    --2015-06-24 08:25:01--  http://localhost:8080/
    Resolving localhost (localhost)... 127.0.0.1
    Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
    HTTP request sent, awaiting response... 200 OK

    java -jar jenkins-cli.jar -s http://localhost:8080/ help

    Jun 24, 2015 8:25:23 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
    SEVERE: I/O error in channel Chunked connection to http://localhost:8080/cli
    java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
	at    hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

     Exception in thread "main" hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
	at hudson.remoting.Request.abort(Request.java:296)
	at hudson.remoting.Channel.terminate(Channel.java:815)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
	at ......remote call to Chunked connection to http://localhost:8080/cli(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
	at hudson.remoting.Request.call(Request.java:171)
	at hudson.remoting.Channel.call(Channel.java:752)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:179)
	at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
	at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1204)
	at hudson.cli.CLI.<init>(CLI.java:145)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:471)
	at hudson.cli.CLI.main(CLI.java:387)
    Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

**Comment by carlossg** [comment]
You need to open the port 50000 for it to work, added to instructions

**Comment by anthonygreen** [comment]
That didn't fix it

**Comment by carlossg** [comment]
works here with port 8080 and 50000
The groovy script sets the jnlp port to 50000 https://github.com/jenkinsci/docker/blob/master/init.groovy#L8

**Comment by anthonygreen** [comment]
Turned out I'd written my own work around to open JNLP on a fixed port and port forward to it. That overwrote the image settings.
