### ISSUE TITLE
Can't reach docker slave

### ISSUE THREAD

**Issue by michel-maier** [jenkinsci/docker#123]
I can't "link" with my docker slave. I retrieve it in the /etc/host of the jenkins container but impossible to ssh it. 
If I map the port directly in the host and I use its ip, its works perfectly. 

[07/15/15 16:49:10] [SSH] Opening SSH connection to jenkins_php56slave_1:1022.
Connection refused
SSH Connection failed with IOException: "Connection refused".
java.io.IOException: There was a problem while connecting to jenkins_php56slave_1:1022
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:587)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1146)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
	at com.trilead.ssh2.Connection.connect(Connection.java:758)
	... 9 more
[07/15/15 16:49:10] Launch failed - cleaning up connection
[07/15/15 16:49:10] [SSH] Connection closed.

**Comment by carlossg** [comment]
what commands are you running?

**Comment by michel-maier** [comment]
Actually, I use a docker-compose file .
```yaml
appli:
    image: jenkins:latest
    ports:
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:50000:50000"
    volumes:
     - jenkins_home/:/var/jenkins_home
    links:
     - php56slave
    environment:
     - JAVA_OPTS=-Dhudson.footerURL=http://server.dev
     - VIRTUAL_HOST=jenkins.server.dev
     - VIRTUAL_PORT=8080
php56slave:
    build: ./docker-file/debian-php-5.6/
    ports:
     - "127.0.0.1:1022:22"
    links:
     - slavepostgre
postgreslave:
  image: postgres:9.4.4
  environment:
   - POSTGRES_PASSWORD=slave-password
   - POSTGRE_USER=postgres

**Comment by ndeloof** [comment]
Can you share the whole project (maybe reduce to minimal set to demonstrate this issue) so we can reproduce and diagnose ?
