### ISSUE TITLE
docker: not found /  docker compose: command not found

### ISSUE THREAD

**Issue by mhabsaoui** [jenkinsci/docker#1251]
### Version report

Jenkins and plugins versions report:

```
Docker image jenkins/jenkins:lts-jdk11
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 20.04.3 LTS  - 64 bits
```

### Reproduction steps

- Step 1 : 
Install Docker and Docker-Compose plugins on Jenkins

- Step 2 :
- Following this example of docker agent => https://www.jenkins.io/doc/book/pipeline/docker/#execution-environment
- Simply running shell for docker-compose `sh "docker-compose up -d"` or `sh '/usr/local/bin/docker-compose up --build'` or using the instruction generator to build the plugin command `step([$class: 'DockerComposeBuilder', dockerComposeFile: 'docker-compose.yml', option: [$class: 'StartAllServices'], useCustomDockerComposeFile: false])` 

- Step 3...
### Results

Expected result:

Pipeline building OK

Actual result: 
Pipeline Fails on docker or  docker-compose  commands : "docker not found" "docker-compose not found"

![image](https://user-images.githubusercontent.com/18755135/145556696-4e27dd2d-d2a4-4785-a951-c84f28611735.png)

![image](https://user-images.githubusercontent.com/18755135/145551845-acf6dbfe-2346-4625-8b29-60fd103dc0d2.png)

**Comment by timja** [comment]
When you're running in docker, docker isn't available.

Generally better to run with an orchestrator that will manage that for you, e.g. Kubernetes.

You can read up on docker in docker but its generally not recommended

Some past issues:

https://github.com/jenkinsci/docker/issues/1221
https://github.com/jenkinsci/docker/issues/263#issuecomment-245263426

**Comment by mhabsaoui** [comment]
Yeah I already knew about DinD, but I thought that Jenkins was out of the box able to (somehow) reach the docker/compose engine that is existing on host...

Then what are the docker/compose plugins of Jenkins useful for ?

**Comment by timja** [comment]
only if you're running on the host or have mounted the socket in

**Comment by mhabsaoui** [comment]
Hi,

So I used a custom Dockerfile to build a complete Jenkins image as follows :

`FROM jenkins/jenkins:2.319.1-jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.25.1 docker-workflow:1.26"`

When running this Jenkinsfile :
`pipeline {
    agent any

    stages {
        // stage('Clone') {
        //     steps {
        //         // Get some code from a Git repository
        //         git branch: 'add-jenkinsfile',
        //            url: 'https://gitbucket.inist.fr/git/istex/sisyphe.git'
        //     }
        // }
        stage('Build') {
            steps {
                // Run Docker-Compose to build images and run services.
                sh 'docker-compose up --build'
            }
            post {
                // Stop and remove containers.
                success {
                    sh 'docker-compose down'
                }
            }
        }
    }
}`


I have Those Errors on docker-compose execution :

`[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] sh
+ docker-compose up --build
[2153] Failed to execute script docker-compose
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 255
Finished: FAILURE`


Thanks for Help...
