### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by mhabsaoui** [jenkinsci/docker#1252]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.319.1
OS: Linux - 5.4.0-1056-gke
---
ace-editor:1.1
ant:1.13
antisamy-markup-formatter:2.5
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
blueocean:1.25.1
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-3
bouncycastle-api:2.20
branch-api:2.7.0
build-timeout:1.20
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:734.v2f848c5e6ea2
cloudbees-folder:6.16
command-launcher:1.2
credentials:2.6.2
credentials-binding:1.27
display-url-api:2.3.5
docker-build-step:2.8
docker-commons:1.17
docker-compose-build-step:1.0
docker-workflow:1.26
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-1
email-ext:2.86
favorite:2.3.3
font-awesome-api:5.15.4-4
git:4.10.0
git-client:3.10.0
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.3
gradle:1.37.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
jackson2-api:2.13.0-230.v59243c64b0a5
jaxb:2.3.0
jdk-tool:1.0
jenkins-design-language:1.25.2
jjwt-api:0.11.2-9.c8b45b8bb173
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
ldap:2.7
lockable-resources:2.12
mailer:1.34
matrix-auth:2.6.11
matrix-project:1.19
momentjs:1.1.1
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:1.12
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.19
plain-credentials:1.7
plugin-util-api:2.6.0
popper-api:1.16.1-2
popper2-api:2.10.2-1
pubsub-light:1.16
resource-disposer:0.16
scm-api:2.6.5
script-security:1.78
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
timestamper:1.15
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1105.v3de5e2efac97
workflow-basic-steps:2.24
workflow-cps:2640.v00e79c8113de
workflow-cps-global-lib:548.v9085a486966a
workflow-durable-task-step:1102.v9c8d2f466adb
workflow-job:2.42
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:613.v375732a042b1
workflow-support:3.8
ws-cleanup:0.39
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 20.04.3 LTS - 64 bits
```

### Reproduction steps

- Step 1: I used a custom Dockerfile to build a complete Jenkins image as follows :

```FROM jenkins/jenkins:2.319.1-jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.25.1 docker-workflow:1.26"
```

- Step 2: After running Jeninks container, I trigger a build with any of those Jenkinsfiles :
- 
```
pipeline {
    agent any
    stages {
       stage('Build') {
            steps {
                // Run Docker-Compose to build images and run services.
                sh 'docker-compose up --build'
            }
            post {
                // Stop and remove containers.
                success {
                    sh 'docker-compose down'
                }
            }
        }
    }
}
```

```
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Run Docker-Compose to build images and run services.
                step([$class: 'DockerComposeBuilder', dockerComposeFile: 'docker-compose.yml', option: [$class: 'StartAllServices'], useCustomDockerComposeFile: false])
            }
            post {
                // Stop and remove containers.
                success {
                    step([$class: 'DockerComposeBuilder', dockerComposeFile: 'docker-compose.yml', option: [$class: 'StopAllServices'], useCustomDockerComposeFile: false])
                }
            }
        }
    }
}

```
### Results

Expected result: Pipeline build OK

Actual result: Pipeline build  Fails with those errors on "docker-compose" execution :

```
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] sh
+ docker-compose up --build
[2153] Failed to execute script docker-compose
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 255
Finished: FAILURE
```

Thanks for Help...

**Comment by timja** [comment]
Same as https://github.com/jenkinsci/docker/issues/1251 ?

docker-compose isn't installed and is unlikely to be.

You can run your agents on a VM with docker is probably a safer bet (and that's what we do, controller in docker agents VM)

**Comment by mhabsaoui** [comment]
And when trying with Docker (ie. to build a docker image, I get this error !
Why isn't it possible for Jenkins to talk to docker deamon ?

![image](https://user-images.githubusercontent.com/18755135/145608802-93eb6ece-4287-453c-8ca5-e247bda6eaed.png)

**Comment by timja** [comment]
you should be able to find plenty on google this is a very common issue and not for this issue tracker

**Comment by mhabsaoui** [comment]
> Same as #1251 ?
> 
> docker-compose isn't installed and is unlikely to be.
> 
> You can run your agents on a VM with docker is probably a safer bet (and that's what we do, controller in docker agents VM)

But, docker+compose are in fact installed, in the Dockerfile. So it should be reachable from inside the container...

**Comment by timja** [comment]
it probably can't reach the docker API then

**Comment by mhabsaoui** [comment]
I verified it by getting inside the container, see ?

> docker exec -it jenkins-ci bash

```
jenkins@aea3cbb1d781:/$ docker -v
Docker version 20.10.11, build dea9396
jenkins@aea3cbb1d781:/$ docker-compose -v
docker-compose version 1.29.2, build 5becea4c
jenkins@aea3cbb1d781:/$ 
```

**Comment by timja** [comment]
does this work: `docker run hello-world`

**Comment by mhabsaoui** [comment]
> does this work: `docker run hello-world`

Nope 0_0

![image](https://user-images.githubusercontent.com/18755135/145610250-7f85bf29-327b-4e86-83d8-47f6925f9614.png)

**Comment by mhabsaoui** [comment]
So we're in the case of DinD, even if installing Docker during image build ?
 
![image](https://user-images.githubusercontent.com/18755135/145612618-448abe9b-191f-4bab-9224-4dde6b7ad3f6.png)

**Comment by timja** [comment]
yes

**Comment by mhabsaoui** [comment]
And then how are we supposed to make CI/CD by pulling docker images ?

I mean is there a recommended way to do it easily, just like on Travis-CI or Circle-CI ?

**Comment by mhabsaoui** [comment]
Just to confirm : Docker is already out of the box

>Starting with Pipeline versions 2.5 and higher, Pipeline has built-in support for interacting with Docker from within a Jenkinsfile.

Right ?

If yes, so nothing special to be installed (ie. plugins, docker engine...) or any settings ?

Thanks
