### ISSUE TITLE
Docker Image: SEVERE: ERROR: Signature verification failed in update site

### ISSUE THREAD

**Issue by abiwill** [jenkinsci/docker#1298]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker Destop 4.3.0
OS: macOS catalina
Jenkins Docker Image: 2.60.x

### Reproduction steps

`docker run --rm --env JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true" -p 8080:8080 -v jenkins  jenkins:2.60.1`

or 

`docker run --rm  -p 8080:8080 -v jenkins  jenkins:2.60.1`

**Error**
```

--> setting agent port for jnlp
--> setting agent port for jnlp... done
Mar 03, 2022 9:53:10 AM hudson.model.UpdateSite updateData
SEVERE: ERROR: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.SignatureException: Signature length not correct: got 512 but was expecting 256<br>	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)<br>	at java.security.Signature$Delegate.engineVerify(Signature.java:1219)<br>	at java.security.Signature.verify(Signature.java:652)<br>	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:444)<br>	at sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)<br>	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)<br>	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)<br>Caused: java.security.cert.CertPathValidatorException: signature check failed<br>	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)<br>	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br>	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br>	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:78)<br>	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:254)<br>	at hudson.model.UpdateSite.updateData(UpdateSite.java:219)<br>	at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:190)<br>	at hudson.model.UpdateCenter.updateDefaultSite(UpdateCenter.java:2194)<br>	at jenkins.install.SetupWizard.init(SetupWizard.java:174)<br>	at jenkins.install.InstallState$3.initializeState(InstallState.java:105)<br>	at jenkins.model.Jenkins.setInstallState(Jenkins.java:1060)<br>at jenkins.install.InstallUtil.proceedToNextStateFrom(InstallUtil.java:96)<br>	at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:950)<br>	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)<br>	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)<br>	at hudson.WebAppMain$3.run(WebAppMain.java:235)<br></pre>
Mar 03, 2022 9:53:10 AM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
```

### Expected Results

Even the log says jenkins server if up and running. We are unable to access the UI. Even the curl http://localhost:8080 results in empty response.

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection 0
```

### Actual Results

UI is not up and running.

**Comment by abiwill** [comment]
Turned out i was using the wrong image.
Need to use jenkins/jenkinstag instead of jenkins:tag

jenkins:tag is now deprecated.
