### ISSUE TITLE
SSL Exception when Downloading Plugins

### ISSUE THREAD

**Issue by AkroutiHamza** [jenkinsci/docker#1354]
### Jenkins and plugins versions report

<details>
  <summary>DockerFile</summary>

  
  ```text
FROM jenkins/jenkins:2.235.1-lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
USER root
RUN wget -q --no-check-certificate https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/plugin-management-parent-pom-2.0.0/jenkins-plugin-manager-2.0.0.jar -O /usr/local/lib/jenkins-plugin-manager.jar
USER jenkins
RUN java -jar /usr/local/lib/jenkins-plugin-manager.jar --war /usr/share/jenkins/jenkins.war --jenkins-update-center http://updates.jenkins.io/current/update-center.actual.json --latest false --verbose -f /usr/share/jenkins/ref/plugins.txt
 ```
 
  ```
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:572)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:596)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:140)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2764)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:566)
        ... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
        at sun.security.validator.Validator.validate(Validator.java:262)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
        ... 25 more
Error getting update center json
 ```
</details>
we are in production we can't upgarde the version of jenkins !

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins:2.235.1

### Reproduction steps

docker build --no-cache -t jenkins:2.235.1-col -f jenkinsdockerfile .

### Expected Results

Plugins Pulled

### Actual Results

SSL Exception when Downloading Plugins

**Comment by timja** [comment]
are you behind a proxy / firewall of some kind? You may need to add a MITM proxy to your trust store

**Comment by timja** [comment]
Certificate seems fine to me, can you retry?

**Comment by AkroutiHamza** [comment]
I have retried with certificate but doesn't work 
could you please send me your dockerfile i thought that i miss something

**Comment by timja** [comment]
https://github.com/hmcts/cnp-jenkins-docker/blob/master/jenkins/Dockerfile

**Comment by AkroutiHamza** [comment]
Unfortunalty doesn't work

**Comment by timja** [comment]
Works fine on GitHub actions. https://github.com/hmcts/cnp-jenkins-docker/runs/6468569877?check_suite_focus=true

Are you building this on your machine or somewhere else?

If you include the full log it should show what mirrors you are hitting (make sure you are using the latest plugin manager CLI, it looks like you've pinned to an older version)

**Comment by timja** [comment]
The plugin manager version you are using is nearly 2 years old.

Please upgrade when you can and then retry.

If you include the full log that may be helpful , you've only included the stacktrace but there should be more information

**Comment by AkroutiHamza** [comment]
@timja please find below all necessary  resources  to reproduce the case 

my plugins.txt
```
subversion:2.13.1
copyartifact:1.44
role-strategy:3.0
antisamy-markup-formatter:2.0
command-launcher:1.4
jquery-ui:1.0.2
workflow-step-api:2.23
m2release:0.16.2
artifactory:3.7.3
github:1.31.0
git-client:3.5.1
javadoc:1.5
windows-slaves:1.6
external-monitor-job:1.7
depgraph-view:1.0.2
ldap:1.24
disk-usage:0.28
config-file-provider:3.6.3
token-macro:2.12
mapdb-api:1.0.9.0
nodejs:1.3.5
maven-invoker-plugin:2.4
ssh-credentials:1.18.1
scm-api:2.6.4
mercurial:2.10
bitbucket:1.1.8
matrix-auth:2.6.1
htmlpublisher:1.23
stashNotifier:1.20
junit:1.29
mailer:1.32.1
matrix-project:1.18
pam-auth:1.6
gradle:1.36
ant:1.11
credentials:2.3.14
structs:1.20
jobConfigHistory:2.26
plain-credentials:1.7
envinject:2.3.0
chromedriver:1.2
ssh-agent:1.19
jquery:1.12.4-1
ssh-slaves:1.31.2
workflow-scm-step:2.11
bouncycastle-api:2.18
handlebars:1.1.1
aws-java-sdk:1.11.723
jdk-tool:1.4
momentjs:1.1.1
veracode-jenkins-plugin:17.2.3.7
jackson2-api:2.11.0
h2-api:1.4.199
cloudbees-folder:6.14
maven-plugin:3.6
next-build-number:1.6
buildtriggerbadge:2.10
pipeline-input-step:2.11
git-server:1.9
durable-task:1.34
pipeline-milestone-step:1.3.1
display-url-api:2.3.2
branch-api:2.5.6
git:4.5.0
stash-pullrequest-builder:1.17
pipeline-build-step:2.12
ace-editor:1.1
pipeline-stage-step:2.3
jquery-detached:1.2.1
workflow-job:2.39
script-security:1.75
workflow-api:2.40
pipeline-graph-analysis:1.10
workflow-support:3.5
workflow-cps:2.80
ivy:2.1
cucumber-reports:5.2.0
workflow-cps-global-lib:2.16
workflow-aggregator:2.6
workflow-multibranch:2.21
pipeline-model-declarative-agent:1.1.1
workflow-basic-steps:2.20
pipeline-aws:1.20
envinject-api:1.7
trilead-api:1.0.8
jsch:0.1.55.2
github-api:1.115
docker-workflow:1.23
junit-attachments:1.6
pipeline-model-definition:1.7.0
greenballs:1.15
plugin-usage-plugin:1.0
build-blocker-plugin:1.7.3
pipeline-rest-api:2.13
pipeline-stage-view:2.13
build-monitor-plugin:1.12+build.201809061734
plot:2.1.7
workflow-durable-task-step:2.35
credentials-binding:1.23
pipeline-model-api:1.7.0
pipeline-maven:3.8.2
pipeline-model-extensions:1.7.0
icon-shim:2.0.3
codedeploy:1.23
authentication-tokens:1.3
docker-commons:1.16
pipeline-stage-tags-metadata:1.7.0
Office-365-Connector:4.13.0
blueocean-pipeline-scm-api:1.23.2
blueocean-jira:1.23.2
variant:1.3
jenkins-design-language:1.23.2
favorite:2.3.2
handy-uri-templates-2-api:2.1.8-1.0
blueocean-github-pipeline:1.23.2
blueocean-display-url:2.3.1
conditional-buildstep:1.3.6
build-failure-analyzer:1.26.0
blueocean-commons:1.23.2
cloudbees-bitbucket-branch-source:2.9.0
blueocean-rest:1.23.2
blueocean-rest-impl:1.23.2
blueocean-bitbucket-pipeline:1.23.2
blueocean-git-pipeline:1.23.2
blueocean-web:1.23.2
pipeline-npm:0.9.2
extended-read-permission:3.2
blueocean-core-js:1.23.2
blueocean-config:1.23.2
blueocean-personalization:1.23.2
run-condition:1.3
blueocean-dashboard:1.23.2
apache-httpcomponents-client-4-api:4.5.10-2.0
blueocean:1.23.2
sse-gateway:1.23
parameterized-trigger:2.36
jira:3.1.1
pipeline-utility-steps:2.6.0
http_request:1.8.26
blueocean-events:1.23.2
okhttp-api:3.14.9
pubsub-light:1.13
blueocean-pipeline-api-impl:1.23.2
lockable-resources:2.8
aws-credentials:1.28
github-branch-source:2.8.3
blueocean-jwt:1.23.2
blueocean-i18n:1.23.2
blueocean-pipeline-editor:1.23.2
blueocean-autofavorite:1.2.4
adoptopenjdk:1.3
openJDK-native-plugin:1.4
allure-jenkins-plugin:2.29.0
zephyr-for-jira-test-management:1.5
monitoring:1.90.0
badge:1.9.1
skip-certificate-check:1.0
caffeine-api:2.9.2-29.v717aac953ff3
performance:1.3.0
```

**Comment by timja** [comment]
I built your Docker image  with the provided casc.yaml and plugins.txt

It failed with:
```
#9 19.41 io.jenkins.tools.pluginmanager.impl.PluginDependencyStrategyException: Plugin blueocean-pipeline-scm-api:1.23.2 depends on blueocean-rest:1.23.2, but there is an older version defined on the top level - blueocean-rest:1.23..13
#9 19.41 	at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:843)
#9 19.41 	at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:484)
#9 19.41 	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:147)
#9 19.41 	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
#9 19.41 	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
#9 19.41 Plugin blueocean-pipeline-scm-api:1.23.2 depends on blueocean-rest:1.23.2, but there is an older version defined on the top level - blueocean-rest:1.23..13
```

but not an ssl exception

**Comment by AkroutiHamza** [comment]
@timja  I think you're right i was  behind proxy that does a man-in-the-middle attack
![image](https://user-images.githubusercontent.com/50912421/168915130-86177b1e-f4a1-4ddf-bd89-8648f525bbac.png)

**Comment by pliniusblah** [comment]
I have tried to build an image but was stopped because similar SSL certificate problem.

Could you help me @timja ?

`
FROM jenkins:1.642.4-alpine
USER root

RUN apk update
RUN apk add curl \
    openssl \
    ca-certificates \
    sudo \
    docker
RUN apk add --no-cache gnupg

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

USER jenkins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
`
