### ISSUE TITLE
HTTP/1.1 400 Bad Request" behind proxy when downloading plugins 

### ISSUE THREAD

**Issue by AkroutiHamza** [jenkinsci/docker#1355]
### Jenkins and plugins versions report

<details>
  <summary>Stack Trace </summary>

  
  ```io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:572)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:591)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:140)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2152)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2764)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:566)
        ... 4 more
Error getting update center json

  ```

Docker File 
  ``` 
FROM jenkins/jenkins:2.235.1-lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
USER root
RUN wget -q --no-check-certificate https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/plugin-management-parent-pom-2.0.0/jenkins-plugin-manager-2.0.0.jar -O /usr/local/lib/jenkins-plugin-manager-2.0.0.jar
USER jenkins
RUN java -Dhttps.proxyHost=x.x.x.x  -Dhttp.proxyHost=x.x.x.x -Dhttp.proxyPort=80 -Dhttps.proxyPort=80 -jar /usr/local/lib/jenkins-plugin-manager-2.0.0.jar  --jenkins-update-center https://updates.jenkins.io/current/update-center.actual.json --latest false --verbose -f /usr/share/jenkins/ref/plugins.txt
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins/jenkins:2.235.1-lts

### Reproduction steps

 docker build --no-cache -t jenkins:2.235.1 -f jenkinsdockerfile .

### Expected Results

Plugins Pulled 

### Actual Results

HTTP/1.1 400 Bad Request"

**Comment by AkroutiHamza** [comment]
Hello @timja 
What informations do you need

**Comment by AkroutiHamza** [comment]
is there a workaround to use http instead of https and avoid SSL exception

**Comment by timja** [comment]
no there's not

**Comment by MarkEWaite** [comment]
Closed issue because it is a proxy issue at the user site, not an issue in the code
