### ISSUE TITLE
Https Connection refused Between Master and Slave agents 

### ISSUE THREAD

**Issue by AkroutiHamza** [jenkinsci/docker#1393]
### Jenkins and plugins versions report

<details>
  <summary>Hello I have Setup secure jenkins instance on docker container and I have disabled http port when bringing up the node 
I am trying to run slave instance on docker conatiner and establish https connection with the master node but i got this error</summary>

  
  ```WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars
Jun 06, 2022 1:00:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://172.17.0.4:443]
Jun 06, 2022 1:00:52 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to https://172.17.0.4:443/tcpSlaveAgentListener/: Connection refused (Connection refused)
java.io.IOException: Failed to connect to https://172.17.0.4:443/tcpSlaveAgentListener/: Connection refused (Connection refused)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:217)
        at hudson.remoting.Engine.innerRun(Engine.java:693)
        at hudson.remoting.Engine.run(Engine.java:518)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
        ... 2 more

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

 jenkins/inbound-agent

### Reproduction steps

docker run -d -v slave1-data:/home/jenkins --name jenkins-slave jenkinsci/inbound-agent -url https://172.17.0.4:443 token  Slave_Worker1

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jenkins == 172.17.0.4

docker run --name jenkins --rm  -p 443:8443 -v $volume_base:/var/jenkins_home --env JENKINS_ADMIN_ID=$JENKINS_INITIAL_ADMIN_NAME --env JENKINS_ADMIN_PASSWORD="$psswrd" jenkins:jcasc --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/usr/share/jenkins/ref/jenkins_keystore.jks --httpsKeyStorePassword="$keytore_pass"

### Expected Results

connection established 

### Actual Results

https connection refused

**Comment by AkroutiHamza** [comment]
@timja

**Comment by MarkEWaite** [comment]
The issue tracker is used to track issues with the docker images.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
