### ISSUE TITLE
Start Jenkins for remote debugging?

### ISSUE THREAD

**Issue by ldtkms** [jenkinsci/docker#151]
Hi,

Thank you for your effort creating official Jenkins images.
I am current start my Jenkins in a docker container.
How would I set the environment variables to start Jenkins container for remote debugging?

I used : "-Xdebug -Xrunjdwp:transport=dt_socket,address=8083,server=y,suspend=n" as JENKINS_OPTS. But I get this error message:

"Caused by: java.lang.IllegalArgumentException: Multiple command line argument specified: -Xrunjdwp:transport=dt_socket,address=8083,server=y,suspend=n
	at winstone.cmdline.CmdLineParser.parse(CmdLineParser.java:68)
	at winstone.Launcher.getArgsFromCommandLine(Launcher.java:361)
	at winstone.Launcher.main(Launcher.java:334)"

Any ideas?

Thanks

**Comment by ldtkms** [comment]
Oops, I fugured out.
It should be JAVA_OPTS instead of JENKINS_OPTS.

Thank you
