### ISSUE TITLE
every update failes from downloading `plugins/ssh-slaves`

### ISSUE THREAD

**Issue by ccppoo** [jenkinsci/docker#1585]
### Jenkins and plugins versions report

Jenkins: 2.394
OS: Linux - 5.10.16.3-microsoft-standard-WSL2
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
ant:481.v7b_09e538fcca
antisamy-markup-formatter:155.v795fb_8702324
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
authentication-tokens:1.4
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-timeout:1.28
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.1
cloud-stats:267.v577e3742c282
cloudbees-folder:6.815.v0dd5a_cb_40e0e
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
config-file-provider:3.11.1
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
display-url-api:2.3.7
docker-build-step:2.9
docker-commons:1.21
docker-compose-build-step:1.0
docker-java-api:3.2.13-68.va_875df25a_b_45
docker-plugin:1.3.0
docker-swarm:1.11
docker-workflow:563.vd5d2e5c4007f
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-1
email-ext:2.94
font-awesome-api:6.2.1-1
git:5.0.0
git-client:4.1.0
github:1.37.0
github-api:1.303-400.v35c2d8258028
github-branch-source:1701.v00cc8184df93
gradle:2.3
h2-api:1.4.199
icon-shim:3.0.0
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jersey2-api:2.39-1
jira:3.9
jjwt-api:0.11.5-77.v646c772fddb_0
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1177.v90374a_ef4d09
ldap:659.v8ca_b_a_fe79fa_d
m2release:0.16.3
mailer:448.v5b_97805e3767
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.21
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
okhttp-api:4.10.0-125.v3593b_a_f8c97b_
pam-auth:1.10
pipeline-build-step:486.vd08f550cceee
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-maven:1257.v89e586d3c58c
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper2-api:2.11.6-2
resource-disposer:0.21
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
ssh-credentials:305.v8f4381501156
ssh-slaves:2.854.v7fd446b_337c9
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3624.v43b_a_38b_62b_b_7
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1282.ve6d865025906
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
yet-another-docker-plugin:0.2.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10 pro

Windows Docker 20.10.23

WSL : windows store's ubuntu 22.04 LTS

running jenkins as build and deploy server (doing everything at single node)

### Reproduction steps

# plugin failes to download ssh-slave

```bash
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi to /var/jenkins_home/plugins/ssh-slaves.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1285)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1319)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1876)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2188)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1850)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

every update that failed ended up with

**Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi**

I tried to install **SSH Agent 327.v230ecd01f86f** plugin but it seems to fail because of `ssh-slave` plugin.

Internet was fine and checked firewall if there was rules that stops from downloading.

container APT package manager was working fine too.

### Expected Results

download plugins and update

### Actual Results

socket timeout

### Anything else?

Logs from docker contianer

```bash
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi to /var/jenkins_home/plugins/ssh-slaves.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1285)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1319)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1876)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2188)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1850)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-13 03:08:54.133+0000 [id=131]	INFO	h.m.UpdateCenter$PluginDowngradeJob#run: Starting the downgrade of docker-plugin on behalf of ccppoo
2023-03-13 03:08:54.134+0000 [id=131]	INFO	h.m.UpdateCenter$PluginDowngradeJob#run: Downgrade successful: docker-plugin
2023-03-13 03:09:40.036+0000 [id=22]	INFO	hudson.PluginManager#install: Starting installation of a batch of 1 plugins plus their dependencies
2023-03-13 03:09:40.038+0000 [id=136]	INFO	h.model.UpdateCenter$DownloadJob#run: Starting the installation of ssh-slaves on behalf of ccppoo
2023-03-13 03:09:40.038+0000 [id=136]	INFO	h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading ssh-slaves
2023-03-13 03:09:46.088+0000 [id=129]	INFO	hudson.model.UpdateCenter#doSafeRestart: Scheduling Jenkins reboot
2023-03-13 03:10:00.122+0000 [id=136]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install ssh-slaves
java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1274)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi to /var/jenkins_home/plugins/ssh-slaves.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1285)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ssh-slaves/2.877.v365f5eb_a_b_eec/ssh-slaves.hpi
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1319)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1876)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2188)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1850)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-13 03:10:00.130+0000 [id=137]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Restart in 10 seconds
2023-03-13 03:10:10.130+0000 [id=137]	INFO	hudson.lifecycle.Lifecycle#onStop: Stopping Jenkins as requested by ccppoo
2023-03-13 03:10:10.132+0000 [id=137]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2023-03-13 03:10:10.144+0000 [id=137]	INFO	jenkins.model.Jenkins$16#onAttained: Started termination
2023-03-13 03:10:10.155+0000 [id=137]	INFO	h.p.b.global.Lifecycle#shutdown: Shutdown complete - Global TimeOut ScheduledExecutorService had 0 tasks pending
2023-03-13 03:10:10.168+0000 [id=137]	INFO	jenkins.model.Jenkins$16#onAttained: Completed termination
2023-03-13 03:10:10.168+0000 [id=137]	INFO	jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2023-03-13 03:10:10.212+0000 [id=137]	INFO	jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2023-03-13 03:10:10.242+0000 [id=137]	INFO	jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2023-03-13 03:10:10.254+0000 [id=137]	INFO	jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2023-03-13 03:10:10.255+0000 [id=137]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
```

```bash
Running from: /usr/share/jenkins/jenkins.war
webroot: /var/jenkins_home/war
2023-03-13 03:10:13.826+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2023-03-13 03:10:13.934+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2023-03-13 03:10:14.033+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-10.0.13; built: 2022-12-07T20:13:20.134Z; git: 1c2636ea05c0ca8de1ffd6ca7f3a98ac084c766d; jvm 11.0.18+10
2023-03-13 03:10:14.512+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2023-03-13 03:10:14.600+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: Session workerName=node0
2023-03-13 03:10:15.330+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2023-03-13 03:10:15.669+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@7ed9ae94{Jenkins v2.387.1,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2023-03-13 03:10:15.718+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@1f59a598{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2023-03-13 03:10:15.752+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started Server@3943a2be{STARTING}[10.0.13,sto=0] @2749ms
2023-03-13 03:10:15.760+0000 [id=40]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2023-03-13 03:10:16.085+0000 [id=46]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2023-03-13 03:10:16.523+0000 [id=83]	INFO	hudson.ClassicPluginStrategy#createPluginWrapper: Plugin yet-another-docker-plugin.jpi is disabled
2023-03-13 03:10:16.549+0000 [id=75]	INFO	hudson.ClassicPluginStrategy#createPluginWrapper: Plugin docker-swarm.jpi is disabled
2023-03-13 03:10:16.585+0000 [id=82]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2023-03-13 03:10:22.732+0000 [id=50]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2023-03-13 03:10:22.753+0000 [id=92]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2023-03-13 03:10:22.758+0000 [id=59]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/var/jenkins_home/war/WEB-INF/lib/groovy-all-2.4.21.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-03-13 03:10:23.375+0000 [id=56]	WARNING	o.j.p.d.DockerBuilder$DescriptorImpl#<init>: Docker URL is not set, docker client won't be initialized
2023-03-13 03:10:23.571+0000 [id=56]	INFO	h.p.b.g.GlobalTimeOutConfiguration#load: global timeout not set
2023-03-13 03:10:24.092+0000 [id=73]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2023-03-13 03:10:24.094+0000 [id=83]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2023-03-13 03:10:24.137+0000 [id=54]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2023-03-13 03:10:24.141+0000 [id=79]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2023-03-13 03:10:24.205+0000 [id=70]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2023-03-13 03:10:24.344+0000 [id=32]	INFO	hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
```

**Comment by ccppoo** [comment]
docker image : jenkins/jenkins:jdk11

is this normal?

```bash
root@501d19b7826d:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

why **127.0.0.11** ?

**Comment by lemeurherve** [comment]
Hello @ccppoo, do you still have this issue?

**Comment by ccppoo** [comment]
@lemeurherve  solved! it was due to fIrewall rules that I didn't manage

thanks
