### ISSUE TITLE
The master Jenkins of the latest LTS JDK17 version reports an error when using SSH to connect to a slave node

### ISSUE THREAD

**Issue by zhangsg1234** [jenkinsci/docker#1689]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

My host is centos7 running in a docker container

### Reproduction steps

1

![image](https://github.com/jenkinsci/docker/assets/43667325/a803208d-8253-43b7-9ddc-32aa53b4f115)

2. This is the error record of my connection
SSHLauncher{host='10.60.200.10', port=22, credentialsId='ec92759b-023d-4739-9dc1-116be1f8e9a2', jvmOptions='', javaPath='/usr/lib/jvm/jenkins-java-home/bin/java', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[08/17/23 18:58:48] [SSH] Opening SSH connection to 10.60.200.10:22.
[08/17/23 18:58:49] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[08/17/23 18:58:49] [SSH] Authentication successful.
[08/17/23 18:58:49] [SSH] The remote user's environment is:
BASH=/usr/bin/bash
BASHOPTS=cmdhist:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="2" [2]="46" [3]="2" [4]="release" [5]="x86_64-redhat-linux-gnu")
BASH_VERSION='4.2.46(2)-release'
DIRSTACK=()
EUID=1007
GROUPS=()
HOME=/home/deploy
HOSTNAME=bank-1
HOSTTYPE=x86_64
ID=1007
IFS=$' \t\n'
JAVA_HOME=/usr/lib/jvm/jdk1.8.0_202
LANG=en_US.UTF-8
LESSOPEN='||/usr/bin/lesspipe.sh %s'
LOGNAME=deploy
MACHTYPE=x86_64-redhat-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/lib/jvm/jdk1.8.0_202/bin:/usr/bin:/bin:/usr/sbin:/sbin
PIPESTATUS=([0]="0")
PPID=27542
PS4='+ '
PWD=/home/deploy
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='10.60.200.26 60500 22'
SSH_CONNECTION='10.60.200.26 60500 10.60.200.10 22'
TERM=dumb
UID=1007
USER=deploy
XDG_RUNTIME_DIR=/run/user/1007
XDG_SESSION_ID=1631
_=/etc/bashrc
[08/17/23 18:58:49] [SSH] Starting sftp client.
[08/17/23 18:58:49] [SSH] Copying latest remoting.jar...
Source agent hash is 25B899E9C1FD1001F55EF1A8DB224323. Installed agent hash is 25B899E9C1FD1001F55EF1A8DB224323
Verified agent jar. No update is necessary.
Expanded the channel window size to 4MB
[08/17/23 18:58:49] [SSH] Starting agent process: cd "/data/jenkins-data" && /usr/lib/jvm/jenkins-java-home/bin/java  -jar remoting.jar -workDir /data/jenkins-data -jar-cache /data/jenkins-data/remoting/jarCache
Aug 17, 2023 6:58:50 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /data/jenkins-data/remoting as a remoting work directory
Aug 17, 2023 6:58:50 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /data/jenkins-data/remoting
<===[JENKINS REMOTING CAPACITY]===>channel started
Remoting version: 3107.v665000b_51092
Launcher: SSHLauncher
Communication Protocol: Standard in/out
This is a Unix agent
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to bank-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1283)
		at org.jenkinsci.plugins.envinject.EnvInjectComputerListener.onOnline(EnvInjectComputerListener.java:144)
		at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:748)
		at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:438)
		at hudson.plugins.sshslaves.SSHLauncher.startAgent(SSHLauncher.java:641)
		at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:458)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @1e9c2d56
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.jenkinsci.plugins.envinject.service.EnvInjectMasterEnvVarsSetter.getModifiers(EnvInjectMasterEnvVarsSetter.java:29)
	at org.jenkinsci.plugins.envinject.service.EnvInjectMasterEnvVarsSetter.call(EnvInjectMasterEnvVarsSetter.java:55)
	at org.jenkinsci.plugins.envinject.service.EnvInjectMasterEnvVarsSetter.call(EnvInjectMasterEnvVarsSetter.java:19)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Agent successfully connected and online

### Expected Results

I don't want an error message

### Actual Results

Now there are errors, but it doesn't affect the use, but I've been worried about what's going on

**Comment by dduportal** [comment]
Hi @zhangsg1234 , what is the java version of the JDK used by the agent process (e.g. `/usr/lib/jvm/jenkins-java-home/bin/java -version` inside the agent) ?

Also, what is the Jenkins version?

**Comment by MarkEWaite** [comment]
Closing as not planned after months without a response.
