### ISSUE TITLE
Use with pre-existing volume

### ISSUE THREAD

**Issue by frapontillo** [jenkinsci/docker#176]
I am trying to start a Jenkins container with a pre-existing volume.
My setup is (latest Docker on Ubuntu 14.04.3):

```shell
docker volume create --name shared-data
docker run -it --name tools -v shared-data:/var/shared ubuntu
mkdir jenkins_home
^C
docker run -t -d --name jenkins -p 8080:8080 -p 50000:50000 -v shared-data:/var/shared \
  --env JENKINS_OPTS="--httpPort=8080" --env JENKINS_HOME="/var/shared/jenkins_home" \
  jenkins
```

But I get the following error:
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Dec 07, 2015 4:22:04 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Dec 07, 2015 4:22:04 PM winstone.Logger logInternal
INFO: Winstone shutdown successfully
Dec 07, 2015 4:22:04 PM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.FileNotFoundException: /var/shared/jenkins_home/war/META-INF/MANIFEST.MF (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:280)
	at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
	at winstone.HostGroup.initHost(HostGroup.java:66)
	at winstone.HostGroup.<init>(HostGroup.java:45)
	at winstone.Launcher.<init>(Launcher.java:143)
	at winstone.Launcher.main(Launcher.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Main._main(Main.java:293)
	at Main.main(Main.java:98)
```

My goal is to save all data not in `/var/jenkins_home` (default), but in `/var/shared/jenkins_home`, that points to my volume.

I have read https://github.com/jenkinsci/docker/issues/155 and https://github.com/jenkinsci/docker/issues/152, among other issues, but haven't been able to come up with a working configuration.

**Comment by nickdgriffin** [comment]
Having exactly the same issue. If I don't name the volume it works fine, but that's not much use when I want to ultimately use a volume driver.

With a named volume the /var/lib/docker/volumes/<vol_name>/_data directory is owned by root, whereas when I omit the volume name it is correctly owned by uid/gid 1000.

**Comment by carlossg** [comment]
It is a permissions issue, the volume is created with root permissions and jenkins runs as user 1000. Either do something to the volume to have the right permissions or run jenkins as root

See https://github.com/jenkinsci/docker/issues/158 for a possible alternative
