### ISSUE TITLE
pipeline-input-step:2.8 Test cases run failed (Server Issue) 

### ISSUE THREAD

**Issue by shivsrivastava** [jenkinsci/docker#1843]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I want to run test cases for pipeline-input-step:2.8 . But after running mvn test, I am getting test failure.
and exception is "[28 10:25:55.417] | Running org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest
[28 10:26:11.601] | Tests run: 6, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 15.963 sec <<< FAILURE! - in org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest
[28 10:26:11.601] | configRoundTrip(org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest)  Time elapsed: 1.55 sec  <<< ERROR!
[28 10:26:11.601] | com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 org/dom4j/DocumentException for http://localhost:46261/jenkins/job/test0/configure
[28 10:26:11.601] | at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:535)
[28 10:26:11.601] | at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:360)"

I have already used JDK - 8 , 11 , 17 but got failed. Please help me with correct JDK, Maven version.

### Reproduction steps

I want to run test cases for pipeline-input-step:2.8 . But after running mvn test, I am getting test failure.
and exception is "[28 10:25:55.417] | Running org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest
[28 10:26:11.601] | Tests run: 6, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 15.963 sec <<< FAILURE! - in org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest
[28 10:26:11.601] | configRoundTrip(org.jenkinsci.plugins.workflow.support.steps.input.InputStepConfigTest)  Time elapsed: 1.55 sec  <<< ERROR!
[28 10:26:11.601] | com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 org/dom4j/DocumentException for http://localhost:46261/jenkins/job/test0/configure
[28 10:26:11.601] | at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:535)
[28 10:26:11.601] | at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:360)"

### Expected Results

Should be pass

### Actual Results

failed

### Anything else?

NA

**Comment by dduportal** [comment]
I'm closing this issue as there are no information to reproduce the problem, to analyze the issue or showing it is related to the official Docker image for Jenkins controllers.

You should open a discussion on the community forum to get help from the whole community at community.jenkins.io.

Also, note the issue templates asking for environment description is there for a reason: if you don't provide this kind of information, chances of getting a solution are close to zero: what is the Jenkins version? How is it installed? What are the installed plugins in which version?

**Comment by meetankit24** [comment]
Getting same above issue for mvn

**Comment by sourabhmagdum45** [comment]
I am also facing same thing.

**Comment by lemeurherve** [comment]
@meetankit24 @sourabhmagdum45 as explained by @dduportal we need more details and context.

**Comment by shivsrivastava** [comment]
> @meetankit24 @sourabhmagdum45 as explained by @dduportal we need more details and context.

Have used JDK 8 , 11 and 17 to run UT cases. Let me know what are required more?

**Comment by dduportal** [comment]
> > @meetankit24 @sourabhmagdum45 as explained by @dduportal we need more details and context.
> 
> Have used JDK 8 , 11 and 17 to run UT cases. Let me know what are required more?

Please read my previous message.

**Comment by shivsrivastava** [comment]
Please find the attached log file.
[build-pipeline-input-step-2.8.txt](https://github.com/jenkinsci/docker/files/14930242/build-pipeline-input-step-2.8.txt)

**Comment by shivsrivastava** [comment]
> > Please find the attached log file. [build-pipeline-input-step-2.8.txt](https://github.com/jenkinsci/docker/files/14930242/build-pipeline-input-step-2.8.txt)
> 
> If you keep ignoring maintainers comment and instructions, you will never get help.
> 
> Last comment before I lock this issue: read my message at [#1843 (comment)](https://github.com/jenkinsci/docker/issues/1843#issuecomment-2034745881) , and follow the instructions by opening a thread in the community forum with the requested information. If we don't know what jenkins version, plugins, pipeline, etc. you are doing, we cannot help.

We have already tried with below information.
Java - 8,11,17
Maven - 3.3.1 to 3.9.4
jenkins - 2.361. 1 

Please let me know , what are correct version to be used.

**Comment by dduportal** [comment]
I'm locking the conversation as the requester does not make the effort to read and follow my instructions. This is not the place for this is issue (community forum are) and no valid information for reproduction or analysis are provided as requested.
