### ISSUE TITLE
Cant add more than one option to JENKINS_OPTS

### ISSUE THREAD

**Issue by kramarz** [jenkinsci/docker#193]
It works with image jenkins:1.625.3 but not with jenkins:latest which is 1.642.1
```
$ docker run -e JENKINS_OPTS="--httpPort=8080 --httpsPort=-1" jenkins
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jan 30, 2016 9:23:52 AM winstone.Logger logInternal 
INFO: Beginning extraction from war file
Jan 30, 2016 9:23:53 AM winstone.Logger logInternal 
INFO: Winstone shutdown successfully
Jan 30, 2016 9:23:53 AM winstone.Logger logInternal
SEVERE: Container startup failed 
java.io.IOException: Failed to start a listener: winstone.HttpConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:211)
        at winstone.Launcher.<init>(Launcher.java:149)
        at winstone.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at Main._main(Main.java:293)
        at Main.main(Main.java:98)
Caused by: java.lang.NumberFormatException: For input string: "8080 --httpsPort=-1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at winstone.cmdline.Option.intArg(Option.java:307)
        at winstone.cmdline.Option$OInt.get(Option.java:219)
        at winstone.HttpConnectorFactory.start(HttpConnectorFactory.java:27)
        at winstone.Launcher.spawnListener(Launcher.java:209)
        ... 8 more
```

**Comment by sergeychipiga** [comment]
It's the result of pull-request https://github.com/jenkinsci/docker/commit/0d1755f00038164928c9f69afa5aa189f740904d.

My pull-request to fix that.

I check that with command:

```bash
docker run -p 80:8080 -e JAVA_OPTS="-Duser.timezone=Europe/Kiev -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\"" jenkins
```

And after launch, system properties were present at http://localhost/systemInfo.

**Comment by dweomer** [comment]
:+1: this is negatively affecting me with multiple "arguments" for both `JAVA_OPTS` and `JENKINS_OPTS`
