### ISSUE TITLE
Alpine images fail a lot of tasks with `ClassNotFoundException`

### ISSUE THREAD

**Issue by Bitals** [jenkinsci/docker#1969]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.489
OS: Linux - 6.1.0-28-amd64
Java: 17.0.13 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
analysis-model-api:12.9.1
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-124.v31e2987e48f4
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
authorize-project:1.8.1
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1200.v4b_a_3da_2eb_db_4
build-name-setter:2.4.3
build-timeout:1.33
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.969.v7d22c6eb_fde1
command-launcher:116.vd85919c54a_d6
commons-compress-api:1.26.1-2
commons-httpclient3-api:3.1-3
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
compress-artifacts:110.vd4a_a_6dde33a_5
conditional-buildstep:1.4.3
config-file-provider:980.v88956a_a_5d6a_d
configuration-as-code:1903.v004d55388f30
configuration-as-code-groovy:1.1
configurationslicing:648.v57e7f26a_6e49
copyartifact:757.v05365583a_455
credentials:1393.v6017143c1763
credentials-binding:687.v619cb_15e923f
dashboard-view:2.521.v339b_a_f4d8da_8
data-tables-api:2.1.8-1
display-url-api:2.209.v582ed814ff2f
docker-commons:445.v6b_646c962a_94
docker-java-api:3.4.0-94.v65ced49b_a_7d5
docker-plugin:1.7.0
durable-task:581.v299a_5609d767
echarts-api:5.5.1-4
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1861.vdb_d991590994
emailext-template:219.v14fff547f78d
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
font-awesome-api:6.6.0-2
forensics-api:2.6.0
generic-webhook-trigger:2.2.5
git:5.6.0
git-changelog:3.41
git-client:6.1.0
git-parameter:0.10.0
git-server:126.v0d945d8d2b_39
github:1.40.0
github-api:1.321-478.vc9ce627ce001
github-branch-source:1807.v50351eb_7dd13
github-checks:589.v845136f916cd
gitlab-api:5.6.0-97.v6603a_83f8690
gitlab-logo:138.v40b_e59380208
gitlab-plugin:1.9.6
groovy:457.v99900cb_85593
groovy-events-listener-plugin:2.240.ve36a_f312f329
gson-api:2.11.0-85.v1f4e87273c33
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jersey2-api:2.44-151.v6df377fff741
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery:1.12.4-3
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1311.v39e1716e4eb_e
ldap:770.vb_455e934581a_
lockable-resources:1327.ved786b_a_197e0
mailer:489.vd4b_25144138f
matrix-auth:3.2.3
matrix-project:840.v812f627cb_578
maven-plugin:3.24
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
nexus-jenkins-plugin:3.20.8-01
okhttp-api:4.11.0-181.v1de5b_83857df
pam-auth:1.11
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-cps-http:0.3.1
pipeline-github-lib:61.v629f2cc41d83
pipeline-global-lib-nexus:0.3.2
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:744.v5b_556ee7c253
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2218.v56d0cda_37c72
pipeline-model-definition:2.2218.v56d0cda_37c72
pipeline-model-extensions:2.2218.v56d0cda_37c72
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2218.v56d0cda_37c72
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
postbuildscript:3.4.1-695.vf6b_0b_8053979
prism-api:1.29.0-18
publish-over:0.22
publish-over-ssh:383.v4eb_4c44da_2dd
rebuild:332.va_1ee476d8f6d
resource-disposer:0.25
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
scm-api:698.v8e3b_c788f0a_6
script-security:1369.v9b_98a_4e95b_2d
secure-post-script:0.1
snakeyaml-api:2.3-123.v13484c65210a_
ssh:158.ve2a_e90fb_7319
ssh-agent:376.v8933585c69d3
ssh-credentials:349.vb_8b_6b_9709f5b_
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
throttle-concurrents:2.16
timestamper:1.28
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
update-sites-manager:2.0.0
variant:60.v7290fc0eb_b_cd
violation-comments-to-gitlab:2.62.0
warnings-ng:11.12.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:4000.v5198556e9cea_
workflow-cps-global-lib-http:2.51.0
workflow-durable-task-step:1398.vf6c9e89e5988
workflow-job:1472.ve4d5eca_143c4
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:936.v9fa_77211ca_e1
ws-cleanup:0.48
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker Hub images:
alpine-jdk21 b54000bd4682
alpine-jdk17 ea7734c0f33e

Host: Debian 12

### Reproduction steps

Run any job using a Docker container agent set up with Docker Cloud plugin (https://plugins.jenkins.io/docker-plugin/)

### Expected Results

It runs, JNLP connection with the agent is established

### Actual Results

```
14:09:33 FATAL: Remote call on JNLP4-connect connection from 172.18.0.1/172.18.0.1:51944 failed
14:09:33 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection to jenkins.local.bitals.xyz/10.10.43.10:50000
14:09:33 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1923)
14:09:33 		at hudson.remoting.Request.call(Request.java:204)
14:09:33 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:312)
14:09:33 		at jdk.proxy2/jdk.proxy2.$Proxy7.fetch3(Unknown Source)
14:09:33 		at hudson.remoting.RemoteClassLoader.prefetchClassReference(RemoteClassLoader.java:363)
14:09:33 		at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:266)
14:09:33 		at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:236)
14:09:33 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
14:09:33 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
14:09:33 		at PluginClassLoader for docker-java-api//com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:134)
14:09:33 		at PluginClassLoader for docker-java-api//com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:124)
14:09:33 		at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$DockerBuildCallable.invoke(DockerBuilderPublisher.java:495)
14:09:33 		at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$DockerBuildCallable.invoke(DockerBuilderPublisher.java:491)
14:09:33 		at Jenkins v2.489//hudson.FilePath$FileCallableWrapper.call(FilePath.java:3593)
14:09:33 		at hudson.remoting.UserRequest.perform(UserRequest.java:225)
14:09:33 		at hudson.remoting.UserRequest.perform(UserRequest.java:50)
14:09:33 		at hudson.remoting.Request$2.run(Request.java:391)
14:09:33 		at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:81)
14:09:33 		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
14:09:33 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:09:33 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:09:33 		at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:140)
14:09:33 		at java.base/java.lang.Thread.run(Unknown Source)
14:09:33 java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.ArchiveEntry
14:09:33 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
14:09:33 	at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:64)
14:09:33 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
14:09:33 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
14:09:33 	at hudson.remoting.RemoteClassLoader$ClassLoaderProxy.fetch4(RemoteClassLoader.java:1073)
14:09:33 	at hudson.remoting.RemoteClassLoader$ClassLoaderProxy.fetch3(RemoteClassLoader.java:1123)
14:09:33 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
14:09:33 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
14:09:33 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:986)
14:09:33 	at hudson.remoting.Request$2.run(Request.java:391)
14:09:33 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:81)
14:09:33 	at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
14:09:33 	at hudson.remoting.CallableDecoratorList.lambda$applyDecorator$0(CallableDecoratorList.java:21)
14:09:33 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
14:09:33 	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
14:09:33 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
14:09:33 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:09:33 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:09:33 	at java.base/java.lang.Thread.run(Unknown Source)
14:09:33 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.18.0.1/172.18.0.1:51944
14:09:33 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1923)
14:09:33 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:384)
14:09:33 		at hudson.remoting.Channel.call(Channel.java:1112)
14:09:33 		at hudson.FilePath.act(FilePath.java:1207)
14:09:33 		at hudson.FilePath.act(FilePath.java:1196)
14:09:33 		at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:407)
14:09:33 		at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:359)
14:09:33 		at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:520)
14:09:33 		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
14:09:33 		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
14:09:33 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:09:33 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
14:09:33 		at hudson.model.Build$BuildExecution.build(Build.java:199)
14:09:33 		at hudson.model.Build$BuildExecution.doRun(Build.java:164)
14:09:33 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:527)
14:09:33 		at hudson.model.Run.execute(Run.java:1833)
14:09:33 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
14:09:33 		at hudson.model.ResourceController.execute(ResourceController.java:101)
14:09:33 		at hudson.model.Executor.run(Executor.java:446)
**14:09:33 Caused: java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/ArchiveEntry**
14:09:33 	at PluginClassLoader for docker-java-api//com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:134)
14:09:33 	at PluginClassLoader for docker-java-api//com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:124)
14:09:33 	at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$DockerBuildCallable.invoke(DockerBuilderPublisher.java:495)
14:09:33 	at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$DockerBuildCallable.invoke(DockerBuilderPublisher.java:491)
14:09:33 	at Jenkins v2.489//hudson.FilePath$FileCallableWrapper.call(FilePath.java:3593)
14:09:33 	at hudson.remoting.UserRequest.perform(UserRequest.java:225)
14:09:33 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
14:09:33 	at hudson.remoting.Request$2.run(Request.java:391)
14:09:33 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:81)
14:09:33 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
14:09:33 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14:09:33 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14:09:33 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:140)
14:09:33 	at java.base/java.lang.Thread.run(Unknown Source)
14:09:33 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 172.18.0.1/172.18.0.1:51944 failed
14:09:33 	at hudson.remoting.Channel.call(Channel.java:1116)
14:09:33 	at hudson.FilePath.act(FilePath.java:1207)
14:09:33 	at hudson.FilePath.act(FilePath.java:1196)
14:09:33 	at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:407)
14:09:33 	at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:359)
14:09:33 	at PluginClassLoader for docker-plugin//com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:520)
14:09:33 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
14:09:33 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
14:09:33 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:09:33 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
14:09:33 	at hudson.model.Build$BuildExecution.build(Build.java:199)
14:09:33 	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
14:09:33 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:527)
14:09:33 	at hudson.model.Run.execute(Run.java:1833)
14:09:33 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
14:09:33 	at hudson.model.ResourceController.execute(ResourceController.java:101)
14:09:33 	at hudson.model.Executor.run(Executor.java:446)
```

### Anything else?

Tried installing [Commons Compress API](https://plugins.jenkins.io/commons-compress-api), [Compress Artifacts](https://plugins.jenkins.io/compress-artifacts), no effect.

**Comment by timja** [comment]
See https://github.com/jenkinsci/docker-java-api-plugin/pull/110

Fixed in https://github.com/jenkinsci/docker-java-api-plugin/releases/tag/3.4.0-95.v80b_75fd32678 which you haven't upgraded to
