### ISSUE TITLE
Alpine-based Jenkins image

### ISSUE THREAD

**Issue by elifarley** [jenkinsci/docker#239]
Some people may want a Jenkins Docker image based on Alpine Linux.

Using Alpine, we can have a working Jenkins image in ~126 MB, as opposed to ~295 MB in the official image (see https://quay.io/repository/elifarley/alpine-jenkins?tab=tags). This minimal image has most of Oracle JDK 8 installed (save for source code, for instance).

My use case is to have a very minimal Jenkins master that will control some build-specific slaves (like one slave for building Java 5 projects, another for Rails projects, and so on).

**Comment by carlossg** [comment]
we can have a branch for it but the official image won't be ported until the java official image is

**Comment by svanoort** [comment]
This is relevant to my interests, so: 

* good news, there's already an official java:8-jdk-alpine label, pulling in at 142 MB vs. 655 MB for mainline java:8-jdk.  
* bad news: it's probably going to break horribly, since the environment is so minimal you don't even get bash. 

My experience with setting up docker environments for packaging & testing Jenkins (testing installs across many distros) was: the more minimal distributions often break in unexpected ways due to missing core utilities.  It takes a trial-and-error process to work through the process of figuring out which missing packages need to be included, and which package names correspond to particular tools.

@elifarley It sounds like you're already docker-proficient and this is of interest, it might be worth starting a PR working towards that goal, since it takes a bit to troubleshoot the issues (and people will probably have helpful advice on challenges encountered along the way).

**Comment by elifarley** [comment]
I've been running a Jenkins master running on an image created with my patch for about 2 days. So far, so good.

I'll be glad to help sort errors out as they appear :)

**Comment by svanoort** [comment]
@elifarley If it works out-of-box, then it shouldn't be hard to just switch it to use the official java Alpine based image (FWIW your PR looks exactly like I would write it), and then people can exercise it a bit to see if there are holes from missing utils or different behaviors.

**Comment by carlossg** [comment]
in alpine branch now

**Comment by carlossg** [comment]
how did you get it to work? jenkins fails to start with 

```
Apr 12, 2016 8:10:01 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.AWTProblem: java.lang.NullPointerException
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at winstone.Launcher.<init>(Launcher.java:156)
	at winstone.Launcher.main(Launcher.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Main._main(Main.java:293)
	at Main.main(Main.java:98)
Caused by: java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.getFamily(Font.java:1220)
	at java.awt.Font.getFamily_NoClientCode(Font.java:1194)
	at java.awt.Font.getFamily(Font.java:1186)
	at java.awt.Font.toString(Font.java:1683)
	at hudson.util.ChartUtil.<clinit>(ChartUtil.java:255)
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:184)
	... 19 more
```

even using `-e JAVA_OPTS=-Djava.awt.headless=true`

**Comment by elifarley** [comment]
Sorry, I've tested with the Oracle JDK version but haven't tested with the OpenJDK one.

I'll probably have to install some fonts to make it work. Will investigate further.

**Comment by carlossg** [comment]
Seems you need `ttf-dejavu`

**Comment by batmat** [comment]
Confirmed. 
Just stumbled into it again working on evergreen and found this. Digging into it, it's actually documented on https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem

I can confirm that I was running Jenkins with the headless sysprop, but still had the NPE:
```
apk add ttf-dejavu
```

Fixed it for me.

**Comment by carlossg** [comment]
@batmat `ttf-dejavu` is already in the alpine image https://github.com/jenkinsci/docker/blob/master/Dockerfile-alpine#L3

**Comment by batmat** [comment]
@carlossg yes, but we're not using it, just taking some bits. And it was not present on https://github.com/jenkins-infra/evergreen/blob/master/Dockerfile#L42
