### ISSUE TITLE
java.io.IOException: Failed to install workflow-step-api plugin on SetupWizard

### ISSUE THREAD

**Issue by dbaba** [jenkinsci/docker#289]
I've been having a trouble with SetupWizard which failed to install some plugins because of workflow-step-api dependency error. And SetupWizard never finished and kept showing Getting Started title with animated progress bar.

It definitely worked approx. 12-18 hours ago but now it doesn't. Why?

Is that caused by some kind of repository errors?

Here is info regarding this issue.

Plugins not installed:
    - GitHub Organization Folder Plugin
    - Credentials Binding Plugin
    - Pipeline

Used Jenkins Images:
    - jenkinsci/jenkins:2.9 with CentOS host and Mac/b2d host
    - jenkinsci/jenkins:2.8 with CentOS host

Docker versions:
```
Docker version 1.11.2, build b9f10c9 # CentOS
Docker version 1.11.0, build 4dc5990 # Mac
```

Weird Jenkins log on startup:
```
WARNING: Could not find dependency structs of workflow-step-api
```

A part of exception stack traces:
```
INFO: Starting the installation of Pipeline: Step API on behalf of admin
Jun 15, 2016 12:56:15 AM hudson.model.UpdateCenter$UpdateCenterConfiguration download
INFO: Downloading Pipeline: Step API
Jun 15, 2016 12:56:15 AM hudson.PluginManager dynamicLoad
INFO: Attempting to dynamic load /var/jenkins_home/plugins/workflow-step-api.jpi
Jun 15, 2016 12:56:15 AM hudson.model.UpdateCenter$DownloadJob run
SEVERE: Failed to install Pipeline: Step API
java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1867)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1624)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to install workflow-step-api plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:834)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:775)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1863)
	... 5 more
Caused by: jenkins.MissingDependencyException: One or more dependencies could not be resolved for workflow-step-api : structs (1.1)
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:529)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:824)
	... 7 more
```

**Comment by carlossg** [comment]
you should ask in the jenkins mailing list as this doesn't seem a docker image problem

**Comment by dbaba** [comment]
Thanks for the reply. I will close this here.

**Comment by meekrosoft** [comment]
Can someone fill in the fix for this problem?  I am seeing the same thing...

**Comment by ravidevops3698** [comment]
java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1383)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to install github plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:508)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1379)
	... 5 more
Caused by: java.io.IOException: Dependency token-macro (1.11), git (2.4.0), github-api (1.69), plain-credentials (1.1) doesn't exist
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
	at hudson.
