### ISSUE TITLE
jenkins 2.11 isn't coming up

### ISSUE THREAD

**Issue by sjeeva** [jenkinsci/docker#301]
Jenkins is failing to come up with below exception 

Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jun 30, 2016 4:58:38 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Logging initialized @585ms
Jun 30, 2016 4:58:38 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
<msg snipped>
Jun 30, 2016 3:11:49 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 9,688 ms
--> setting agent port for jnlp
--> setting agent port for jnlp... done
Jun 30, 2016 3:14:39 PM hudson.ExpressionFactory2$JexlExpression evalu                                                                    ate
WARNING: Caught exception evaluating: request.getSession() in /static/                                                                    c36f0adf/css/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_lati                                                                    n_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.woff. Reason: java.la                                                                    ng.IllegalStateException: Response is committed
java.lang.IllegalStateException: Response is committed
        at org.eclipse.jetty.server.Request.getSession(Request.java:14                                                                    00)
        at org.eclipse.jetty.server.Request.getSession(Request.java:13                                                                    78)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(Htt                                                                    pServletRequestWrapper.java:279)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcc                                                                    essorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingM                                                                    ethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.jexl.util.introspection.UberspectImpl$Ve                                                                    lMethodImpl.invoke(UberspectImpl.java:258)
        at org.apache.commons.jexl.parser.ASTMethod.execute(ASTMethod.                                                                    java:104)
        at org.apache.commons.jexl.parser.ASTReference.execute(ASTRefe                                                                    rence.java:83)
        at org.apache.commons.jexl.parser.ASTReference.value(ASTRefere                                                                    nce.java:57)
        at org.apache.commons.jexl.parser.ASTReferenceExpression.value                                                                    (ASTReferenceExpression.java:51)
        at org.apache.commons.jexl.ExpressionImpl.evaluate(ExpressionI                                                                    mpl.java:80)
        at hudson.ExpressionFactory2$JexlExpression.evaluate(Expressio                                                                    nFactory2.java:74)
        at org.apache.commons.jelly.tags.core.CoreTagLibrary$3.run(Cor                                                                    eTagLibrary.java:134)
        at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.j                                                                    ava:95)
        at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(Cor                                                                    eTagLibrary.java:105)
        at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibSc                                                                    ript.java:120)
        at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.j                                                                    ava:95)
        at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(Cor                                                                    eTagLibrary.java:105)
        at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScri                                                                    pt.java:95)
        at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript                                                                    (DefaultScriptInvoker.java:63)
        at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript                                                                    (DefaultScriptInvoker.java:53)
        at org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.                                                                    java:95)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at hudson.init.impl.InstallUncaughtExceptionHandler$1.reportEx                                                                    ception(InstallUncaughtExceptionHandler.java:30)
        at org.kohsuke.stapler.compression.CompressionFilter.reportExc                                                                    eption(CompressionFilter.java:77)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(                                                                    CompressionFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilt                                                                    er(ServletHandler.java:1652)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncod                                                                    ingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilt                                                                    er(ServletHandler.java:1652)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(Dia                                                                    gnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilt                                                                    er(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHa                                                                    ndler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(Scope                                                                    dHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityH                                                                    andler.java:553)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(Se                                                                    ssionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(Co                                                                    ntextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHan                                                                    dler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(Ses                                                                    sionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(Con                                                                    textHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(Scope                                                                    dHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(Hand                                                                    lerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.jav                                                                    a:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConn                                                                    ection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConne                                                                    ction.java:544)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorServic                                                                    e.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo                                                                    lExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo                                                                    olExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ndeloof** [comment]
Can you please confirm this issue is docker image specific ? Just run jenkins 2.11 and confirm this issue doesn't appear

**Comment by sjeeva** [comment]
I am not seeing this issue in the newer version, so closing this issue
