### ISSUE TITLE
Cannot set proxy authentication method through -Dhttp.auth.preference

### ISSUE THREAD

**Issue by ste26054** [jenkinsci/docker#324]
Hi,

I am trying to setup a proxy authentication different from NTLM.

So my docker run command is the following:

`docker run -p 20080:8080 -p 50000:50000 -v /home/docker/jenkins:/var/jenkins_home --env JAVA_OPTS=-Dhttp.auth.preference=basic jenkins`

However when checking later the proxy credentials (when setting up Jenkins), I get:

`Aug 05, 2016 4:39:28 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Aug 05, 2016 4:40:30 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: ntlm authentication scheme selected
Aug 05, 2016 4:40:30 PM org.apache.commons.httpclient.HttpMethodDirector authenticate
SEVERE: Credentials cannot be used for NTLM authentication: org.apache.commons.httpclient.UsernamePasswordCredentials
org.apache.commons.httpclient.auth.InvalidCredentialsException: Credentials cannot be used for NTLM authentication: org.apache.commons.httpclient.UsernamePasswordCredentials
        at org.apache.commons.httpclient.auth.NTLMScheme.authenticate(NTLMScheme.java:332)
        at org.apache.commons.httpclient.HttpMethodDirector.authenticateProxy(HttpMethodDirector.java:320)
        at org.apache.commons.httpclient.HttpMethodDirector.authenticate(HttpMethodDirector.java:232)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at hudson.ProxyConfiguration$DescriptorImpl.doValidateProxy(ProxyConfiguration.java:367)`

Jenkins does not seem to pick the `basic` authentication method.  Do you know why ?

**Comment by ndeloof** [comment]
Does this work with a non-docker jenkins ?
