### ISSUE TITLE
Jenkins can't access internet on QNAP device

### ISSUE THREAD

**Issue by core23** [jenkinsci/docker#358]
I try to get the docker image (1.651.3 or latest version) running on my QNAP NAS using the internal ContainerStation.

Just using the default settings without setting any parameters or binding any resource, I can't access the internet. I already tried the NAT or Host network mode, but this would make no difference.

**Stacktrace**
```
Oct 02, 2016 1:55:07 PM javax.jmdns.impl.HostInfo newHostInfo                                                                   
WARNING: Could not intialize the host network interface on nullbecause of an error: 5929616b9f0b: 5929616b9f0b: unknown error   
java.net.UnknownHostException: 5929616b9f0b: 5929616b9f0b: unknown error                                                        
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)                                                             
        at javax.jmdns.impl.HostInfo.newHostInfo(HostInfo.java:75)                                                              
        at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:407)                                                                
        at javax.jmdns.JmDNS.create(JmDNS.java:60)                                                                              
        at hudson.DNSMultiCast$1.call(DNSMultiCast.java:32)                                                                     
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)                         
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                             
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                      
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                      
        at java.lang.Thread.run(Thread.java:745)                                                                                
Caused by: java.net.UnknownHostException: 5929616b9f0b: unknown error                                                           
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)                                                           
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)                                                       
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)                                              
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)                                                             
        ... 9 more    
```

**Using bash:**
```
$ ping google.de                                                                                                                                                         
ping: unknown host  
```

Any idea what might be the problem? Any other docker image can access the internet, only this image has these problems.

**Comment by carlossg** [comment]
This has to be a problem with your docker installation

**Comment by core23** [comment]
Any idea how to find out what could be wrong?

**Comment by ndeloof** [comment]
if you can't get a simple ping to work, this is unrelated to jenkins' docker image, so please join docker forum to get support.
