### ISSUE TITLE
Dependent plugins is not installing.

### ISSUE THREAD

**Issue by harish-kumar-garg** [jenkinsci/docker#367]
My 
plugins.txt file contains:
sonar:2.4.4

Dockerfile file contains:
FROM jenkins
MAINTAINER HarishGarg
COPY plugins.txt /plugins.txt
RUN /usr/local/bin/plugins.sh /plugins.txt

Building docker image by "docker build -t detest/jenkinshg:latest ." is successful.

But while running docker image by "docker run -p 8080:8080 --name=jenkins-master detest/jenkinshg:latest"
installing sonar:2.4.4 plugin, I am getting below message:

INFO: Listed all plugins
Oct 13, 2016 10:52:42 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Jenkins SonarQube Plugin v2.4.4 (sonar)
java.io.IOException: Jenkins SonarQube Plugin v2.4.4 failed to load.
 - jquery v1.11.2-0 is missing. To fix, install v1.11.2-0 or later.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:1026)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by carlossg** [comment]
Plugins.sh does not resolve transitive dependencies, use install-plugins.sh
