### ISSUE TITLE
Installing maven downgrades JRE

### ISSUE THREAD

**Issue by frangarcia** [jenkinsci/docker#477]
I have this Dockerfile

```
# Pull base image.
FROM jenkinsci/jenkins:latest

MAINTAINER Fran Garcia <me@email.com>

#Changing to root user to install some packages
USER root

# Installing necessary packages
RUN apt-get update && apt-get -y install maven

# Expose
EXPOSE 8080
EXPOSE 50000

WORKDIR /var/jenkins_home
```

### Docker commands that you execute

```
docker build --no-cache=true --rm -t jenkins .
docker run -d -p 8383:8080 -p 50000:50000 --name my_jenkins jenkins
```

### Actual result

Jenkins doesn't start up with this error. 

```
Apr 25, 2017 9:01:06 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Apr 25, 2017 9:01:06 AM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Failed startup of context w.@6e75bb62{/,file:/var/jenkins_home/war/,STARTING}{/var/jenkins_home/war}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:408)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1340)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at winstone.Launcher.<init>(Launcher.java:152)
	at winstone.Launcher.main(Launcher.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at Main._main(Main.java:264)
	at Main.main(Main.java:112)
Caused by: java.lang.UnsupportedClassVersionError: jenkins/util/SystemProperties : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:510)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:441)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1583)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1956)
	... 25 more

Apr 25, 2017 9:01:06 AM org.eclipse.jetty.util.log.JavaUtilLog info
```

### Expected outcome

Jenkins should start up

### Output of `docker version`

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

### Other relevant information

OS: Mac OS X

If I remove the installation of maven, it works fine.

**Comment by carlossg** [comment]
probably a different openjdk gets installed when you install maven

**Comment by frangarcia** [comment]
It seems so, to be honest, it looks more a problem with the 8-jdk docker image than with jenkins one. If you ssh the jenkins container you can see a bunch of jre/jdk installed so it is a bit weird.

**Comment by frangarcia** [comment]
I have created an issue directly on openjdk docker repository as I think it is a problem with that image, not with Jenkins one. For the record, this is the issue https://github.com/docker-library/openjdk/issues/110.

Closing this one.

**Comment by frangarcia** [comment]
Again for the records, https://github.com/docker-library/openjdk/issues/110 has been fixed so it shouldn't be any problem installing maven in a jenkins container.
