### ISSUE TITLE
Disk quota exceeded on 25Gb free space

### ISSUE THREAD

**Issue by tevel** [jenkinsci/docker#545]
docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

result:

Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Exception in thread "main" java.io.IOException: Disk quota exceeded
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at Main.copyStream(Main.java:380)
	at Main.extractFromJar(Main.java:405)
	at Main._main(Main.java:230)
	at Main.main(Main.java:132)

df -h 
Filesystem            Size  Used Avail Use% Mounted on
udev                  478M     0  478M   0% /dev
tmpfs                 100M  4.4M   95M   5% /run
/dev/mapper/vg0-root   34G  7.1G   25G  23% /
tmpfs                 497M     0  497M   0% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
tmpfs                 497M     0  497M   0% /sys/fs/cgroup
/dev/mapper/vg0-boot  461M  145M  293M  33% /boot
/dev/mapper/vg0-tmp   1.9G  2.9M  1.8G   1% /tmp

run on VPS
CPU: 1 Cores
RAM: 1GB
SSD: 40GB

**Comment by carlossg** [comment]
something is wrong with your docker setup
