### ISSUE TITLE
jenkins/jenkins:lts - public GPG keys from Ubuntu-16.04 unavailable

### ISSUE THREAD

**Issue by daixtrose** [jenkinsci/docker#567]
### Summary

Creating an extended Dockerfile from `jenkins/jenkins:lts` as described in chapter [Installing More Tools](https://github.com/jenkinsci/docker/blob/master/README.md#installing-more-tools) fails with
```bash
GPG error: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E9377A2BA9EF27F
W: The repository 'http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease' is not signed.
```

It looks like the relevant keys have been deleted. Any idea how to mend this?

### Dockerfile in use

```docker
FROM jenkins/jenkins:lts
# This here would work fine
# FROM ubuntu:16.04

# Install packages via apt
USER root

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y apt-utils curl software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test


RUN curl -sSL https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz | tar -xzC /opt
ENV PATH="/opt/cmake-3.9.1-Linux-x86_64/bin:$PATH"

RUN curl https://apt.llvm.org/llvm-snapshot.gpg.key > /tmp/llvm-snapshot.gpg.key \
    && apt-key add /tmp/llvm-snapshot.gpg.key \
    && add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main"

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
        clang-5.0 \
        clang-tidy-5.0 \
        g++-6 \
        gcc-6 \
        git-core \ 
        libboost-all-dev \
        make \
    && rm -rf /build/* \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf /usr/share/doc/* \
    && rm -rf /var/lib/apt/lists/* 

RUN /usr/local/bin/install-plugins.sh github-pullrequest 
#    github-branch-source:1.8

# drop back to the regular jenkins user - good practice
USER jenkins
```

### Docker commands that you execute

```bash
sudo docker build -t jenkins .
```
### Actual result

```bash
[ ... irrelevant output skipped ...]
Step 5/11 : RUN DEBIAN_FRONTEND=noninteractive     && apt-get update     && apt-get install -y apt-utils curl software-properties-common     && add-apt-repository ppa:ubuntu-toolchain-r/test
 ---> Using cache
 ---> fd2e6654c623
Step 6/11 : RUN curl -sSL https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz | tar -xzC /opt
 ---> Using cache
 ---> c1d359973f0c
Step 7/11 : ENV PATH "/opt/cmake-3.9.1-Linux-x86_64/bin:$PATH"
 ---> Using cache
 ---> 4b70db9fb0a6
Step 8/11 : RUN curl https://apt.llvm.org/llvm-snapshot.gpg.key > /tmp/llvm-snapshot.gpg.key     && apt-key add /tmp/llvm-snapshot.gpg.key     && add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main"
 ---> Using cache
 ---> ec3028e06d38
Step 9/11 : RUN DEBIAN_FRONTEND=noninteractive apt-get update     && apt-get install -y         clang-5.0         clang-tidy-5.0         g++-6         gcc-6         git-core         libboost-all-dev         make     && rm -rf /build/*     && rm -rf /tmp/* /var/tmp/*     && rm -rf /usr/share/doc/*     && rm -rf /var/lib/apt/lists/*
 ---> Running in dbb92f751dcb
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch-updates InRelease
Hit:3 http://security.debian.org stretch/updates InRelease
Get:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease [15.4 kB]
Hit:5 http://deb.debian.org/debian stretch Release
Ign:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease
Get:7 http://apt.llvm.org/xenial llvm-toolchain-xenial-5.0 InRelease [4236 B]
Get:8 http://apt.llvm.org/xenial llvm-toolchain-xenial-5.0/main amd64 Packages [7387 B]
Fetched 27.0 kB in 0s (28.2 kB/s)
Reading package lists...
W: GPG error: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E9377A2BA9EF27F
W: The repository 'http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu artful InRelease' is not signed.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-5.0 : Depends: libstdc++-5-dev but it is not installable
             Depends: libgcc-5-dev but it is not installable
             Depends: libobjc-5-dev but it is not installable
             Recommends: llvm-5.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update     && apt-get install -y         clang-5.0         clang-tidy-5.0         g++-6         gcc-6         git-core         libboost-all-dev         make     && rm -rf /build/*     && rm -rf /tmp/* /var/tmp/*     && rm -rf /usr/share/doc/*     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
### Expected outcome

Run through without error as with `FROM ubuntu:16.04`

### Have you tried a non-dockerized Jenkins and get the expected outcome?

Nope. This is Docker specific.

### Output of `docker version`

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by daixtrose** [comment]
One additional comment: An attempt to manually install the missing key using `apt-key`

```
RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y apt-utils curl software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F`
```
also fails with

```
gpg: keybox '/tmp/tmpzypyh4ig/pubring.gpg' created
gpg: /tmp/tmpzypyh4ig/trustdb.gpg: trustdb created
gpg: key 1E9377A2BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'
```

**Comment by rtyler** [comment]
The `lts` image is based on `openjdk:8-jdk` which is itself based on Debian 9 Stretch.

Comparing Debian behavior to Ubuntu behavior I don't think is an issue for this repository.
