### ISSUE TITLE
Failed to listen to incoming slave connection

### ISSUE THREAD

**Issue by jgillich** [jenkinsci/docker#6]
Running the latest tag on CentOS 7 & Docker 0.11.1, Jenkins fails to bind the port:

```
Failed to listen to incoming slave connection

java.net.BindException: Failed to listen on port 50000 because it's already in use.
    at hudson.TcpSlaveAgentListener.<init>(TcpSlaveAgentListener.java:75)
    at jenkins.model.Jenkins.<init>(Jenkins.java:825)
    at hudson.model.Hudson.<init>(Hudson.java:82)
    at hudson.model.Hudson.<init>(Hudson.java:78)
    at hudson.WebAppMain$3.run(WebAppMain.java:222)
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
    at hudson.TcpSlaveAgentListener.<init>(TcpSlaveAgentListener.java:73)
    ... 4 more
```

The port isn't used on the host.

**Comment by Ohadbasan** [comment]
I still hit that problem.
wasn't it fixed?

thanks

**Comment by michaelneale** [comment]
Yes it should be using the init groovy. @ndeloof is the init.groovy still in use that sets the fixed slave port?

**Comment by ndeloof** [comment]
yes it is https://github.com/cloudbees/jenkins-ci.org-docker/blob/master/Dockerfile#L22

**Comment by holmesb** [comment]
Still having this 'port 50000 already in use' problem in current LTS Jenkins release, running on Kubernetes.   Restarting the Jenkins container within the pod seems a valid workaround.  Prob still timing issues during startup.

**Comment by nitish-predera** [comment]
I was having the same issue after restoring Jenkins backup to my Jenkins setup. It was deployed using Helm charts on a Kubernetes cluster. 

Manage Jenkins > Configure Global Security > Agents

Disable the setting "TCP port for inbound agents" and **Apply**, then undo the radio to Fixed: `50000` option and save. 

Worked for me.
