### ISSUE TITLE
git ls-remote --symref git@XXX.git" returned status code 128

### ISSUE THREAD

**Issue by edugueperouxWeborama** [jenkinsci/docker#643]
### Docker commands that you execute
docker run --name jenkins --dns 8.8.8.8 -p 8080:8080 -p 50000:50000 -v jenkins_home2:/var/jenkins_home jenkins/jenkins

Create a "Multibranch Pipeline" and define "Branch Sources" to a gitlab repo with git@ scheme and a private key auth.
### Actual result
ERROR: [Tue Feb 20 15:19:05 UTC 2018] Could not update folder level actions from source f1eff320-d164-4be5-961d-12303bae8c82
hudson.plugins.git.GitException: Command "git ls-remote --symref git@gitlab.com:XXX.git" returned status code 128:
stdout: 
stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1625)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1616)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getRemoteSymbolicReferences(CliGitAPIImpl.java:2873)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieveActions(AbstractGitSCMSource.java:937)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:746)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:588)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)

### Expected outcome
I expected to have a working source.
The issue seem a too old git version installed in docker image.

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No

### Output of `docker version`
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by edugueperouxWeborama** [comment]
I have used latest image since lts tag failed to resolve dns to install plugins.

**Comment by carlossg** [comment]
why would git be too old?
error is due to permissions `Permission denied (publickey).`

**Comment by edugueperouxWeborama** [comment]
When I execute "git ls-remote --symref git@gitlab.com:XXX.git" in the container I get a message error saying that "--symref" option is not recognized.

**Comment by batmat** [comment]
Also, as you're not running a specific sha for the image, there's no way to be sure what version you're on.

What does the following output on the faulty machine?
```
docker images --digests | grep jenkins
```

**Comment by carlossg** [comment]
cannot reproduce

**Comment by Lectorrr** [comment]
is  the problem caused by the version of git too low？
