### ISSUE TITLE
An error occurred during installation: No such plugin: cloudbees-folder 

### ISSUE THREAD

**Issue by jpergega2006** [jenkinsci/docker#649]
I have got Jenkins **version 2.108**

**Steps:**
1. I downloaded Weekly support Jenkins-2.108 
2. I installed the Jenkins via Jenkins.msi 
3. When the initial http://localhost:8080/ opened it asked me to unlock Jenkins so I did that.
4. Then it asked me to Install Suggested Plugins but is giving me the error: 
`An error occurred during installation: No such plugin: cloudbees-folder `
5. I tried Select Plugins to Install but I'm getting the same error. 
6. I closed the Jenkins URL then went to Command Line cd into Jenkins folder and typed java -jar jenkins.war 
7. Then I can see the red error messages in my command line:
```
Mar 07, 2018 12:05:54 PM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.IOException: Failed to start Jetty
        at winstone.Launcher.<init>(Launcher.java:156)
        at winstone.Launcher.main(Launcher.java:354)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at Main._main(Main.java:309)
        at Main.main(Main.java:132)
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:29
8)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet
workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java
:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:431)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at winstone.Launcher.<init>(Launcher.java:154)
        ... 7 more
```
I have tried use different port 8081 but I'm still getting the same issue. Please help

**Comment by carlossg** [comment]
> I installed the Jenkins via Jenkins.msi

This repo is for the docker image, you should ask in the users mailing list https://jenkins.io/mailing-lists/

**Comment by sagary2j** [comment]
@jpergega2006 
It's the issue with java process running in background. Just kill the process if you are using windows go to task manager and kill the java process and try to run Jenkins again. It will definitely solve your problem.

**Comment by jineshsubedi** [comment]
unchecked all selected plugin suggested by Jenkins and run

**Comment by nadeemIqbal02** [comment]
Restarting Machine solved the issue

**Comment by iamfip** [comment]
> Restarting Machine solved the issue

Yeah it works!!
