### ISSUE TITLE
Since jenkins 2.114 - Failed to create a temporary file in /var/jenkins_home

### ISSUE THREAD

**Issue by MichaelGreco** [jenkinsci/docker#666]
I create jenkins using a volume so that I can back up my jenkins data : 

docker run --name orchestration -d -p 8080:8080 -p 50000:50000 -v orchestration:/var/jenkins_home jenkins/jenkins  

Now since 2.114 If I start up with data existing in /var/jenkins_home then I get the following error : 

java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:142)
Caused: java.io.IOException: Failed to create a temporary file in /var/jenkins_home
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:144)
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:109)
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:84)
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:74)
	at hudson.XmlFile.write(XmlFile.java:187)
	at jenkins.model.Jenkins.save(Jenkins.java:3169)
	at jenkins.model.Jenkins.<init>(Jenkins.java:921)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)

**Comment by MichaelGreco** [comment]
I had to do this : 

docker run --name bash -i -t -d -v orchestration:/var/jenkins_home bash
docker exec -i -t bash bash
cd /var/jenkins_home
chmod 777 .

and then exit and then all was happy ...

**Comment by carlossg** [comment]
what permissions did the files in your orchestration volume have?

**Comment by jlegido** [comment]
First of all many thanks to all the people investing their time in this project.

Just for the records in my case the issue is that the docker host user who ran the container has UID 10000, leading to this inside the container:

```
ls -ld /var/jenkins_home
drwxr-xr-x 13 10000 10000 4096 Apr  2 08:29 /var/jenkins_home
```

So I guess this should be considered a bug.
I'll do my best to fill it.
