### ISSUE TITLE
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?

### ISSUE THREAD

**Issue by meghalidhoble** [jenkinsci/docker#677]
I am getting "permission denied" error while running the docker container using mounted volumes, command used as below: 
    
  `   $  docker run -p 8080:8080 -p 50000:50000 -v /jenkins:/var/jenkins_home jenkins:lts`

Please note that /Jenkins is the host mount path/folder and “/var/Jenkins_home” is the container volume being mounted. 
I observed that the container is using "jenkins" user with UID & GID being set to 1000. However on host the user ‘jenkins’ has different values for UID & GID.
Another problem is that UID=1000 is already being used for some other user on host VM.  Hence can't change the UID/ GID for the host ‘jenkins’ user.

As per the issues list on github;  many people have faced this issue and most of the places it has suggested to change the permission and owner of the host directory, using "chown -R 1000:1000 <host_mount_path> ".

However I think changing the permissions to some other user’s permission can cause issues on production and could lead to a security concern. 
The better solution would be to accept argument for UID & GID while running the container. I have tried this approach by modifying the dockerfile locally and it worked fine for me. 

Please let me know your comments/suggestions around this. 

Thanks,
Meghali Dhoble

**Comment by meghalidhoble** [comment]
Thanks @carlossg for the response.  The solution at #177 helped me to get through.  i.e. using "- u <user_id>". 
I was using "user_name" instead use of "user_id" helped. I think its worth mentioning this point, at the README page, as many of the users facing same issue.

**Comment by batmat** [comment]
@meghalidhoble note that #177 is also a workaround, aka not a durable solution. I described what is the recommended solution at https://github.com/jenkinsci/docker/issues/493#issuecomment-387722074

**Comment by anmolmore15** [comment]
@batmat  

I am getting following error after following your solution:

WARNING: Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2662)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2584)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1770)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at hudson.model.DownloadService.loadJSON(DownloadService.java:166)
        at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:176)
        at hudson.model.UpdateCenter.updateDefaultSite(UpdateCenter.java:2181)
        at jenkins.install.SetupWizard.init(SetupWizard.java:170)
        at jenkins.install.InstallState$3.initializeState(InstallState.java:105)
        at jenkins.model.Jenkins.setInstallState(Jenkins.java:970)
        at jenkins.install.InstallUtil.proceedToNextStateFrom(InstallUtil.java:94)
        at jenkins.model.Jenkins.<init>(Jenkins.java:887)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:227)

**Comment by batmat** [comment]
@anmolmore15 AFAICT, this issue seems more related to some transient network problem than what I was talking about. Is this something you can reproduce? Thanks

**Comment by afnanqureshi** [comment]
I was getting the same error when I was trying to run jenkins on aws ECS-fargate and mounting the volume on EFS. I resolved this issue by changing the user in my Dockerfile to root.
```USER root```

**Comment by harshblog150** [comment]
Hi guys, 
getting similar issue - i was trying mount my local-machine All jenkins configurations (including plugins, jobs, workspace) everything into a new jenkins container... No Luck!

[jenkins@ip-10-0-1-12 jenkins]$ chown -R 1001:1001 /home/jenkins/jenkins_home/jenkins

[jenkins@ip-10-0-1-12 jenkins]$ docker run -dit --name Jenkins_Container -p 8084:8080 -p 50000:50000 -v /home/jenkins/jenkins_home/jenkins:/var/jenkins_home jenkins/jenkins:lts-jdk11
57b867bc7a442f5b326153c9454bb8d4dc4989174338c5321d93f0b24ba0da1e
[jenkins@ip-10-0-1-12 jenkins]$ docker ps -a
CONTAINER ID   IMAGE                                            COMMAND                  CREATED         STATUS                     PORTS                                                           NAMES
57b867bc7a44   jenkins/jenkins:lts-jdk11                        "/sbin/tini -- /usr/…"   4 seconds ago   Exited (1) 3 seconds ago

[jenkins@ip-10-0-1-12 jenkins]$ docker logs -f 57b867bc7a44
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
