### ISSUE TITLE
CertificateException: No subject alternative DNS name matching updates.jenkins.io found.

### ISSUE THREAD

**Issue by rvernica** [jenkinsci/docker#727]
I get a `javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching updates.jenkins.io found.` exception when starting the Jenkins container. The container does end up starting, but when I access the UI for the first time and install the recommended plugins, I get `An error occurred during installation: No such plugin: cloudbees-folder `. I am using a web proxy to access the internet and the proxy is set in Docker as well as in the container (see below). 

 Here is what I get when starting the container:
```bash
> docker-compose up ci
Creating volume "trunk_ci" with default driver
Creating trunk_ci_1 ... done
...
ci_1     | Sep 17, 2018 1:56:48 PM hudson.model.UpdateCenter updateDefaultSite
ci_1     | WARNING: Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.
ci_1     | javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching updates.jenkins.io found.
ci_1     | 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
ci_1     | 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
ci_1     | 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
ci_1     | 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
ci_1     | 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
ci_1     | 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
ci_1     | 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
ci_1     | 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
ci_1     | 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
ci_1     | 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
ci_1     | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
ci_1     | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
ci_1     | 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
ci_1     | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
ci_1     | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
ci_1     | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
ci_1     | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
ci_1     | 	at hudson.model.DownloadService.loadJSON(DownloadService.java:167)
ci_1     | 	at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:185)
ci_1     | 	at hudson.model.UpdateCenter.updateDefaultSite(UpdateCenter.java:2185)
ci_1     | 	at jenkins.install.SetupWizard.init(SetupWizard.java:179)
ci_1     | 	at jenkins.install.InstallState$InitialSecuritySetup.initializeState(InstallState.java:164)
ci_1     | 	at jenkins.model.Jenkins.setInstallState(Jenkins.java:1039)
ci_1     | 	at jenkins.install.InstallUtil.proceedToNextStateFrom(InstallUtil.java:97)
ci_1     | 	at jenkins.install.InstallState$Unknown.initializeState(InstallState.java:82)
ci_1     | 	at jenkins.model.Jenkins$17.run(Jenkins.java:3201)
ci_1     | 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
ci_1     | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
ci_1     | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
ci_1     | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
ci_1     | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
ci_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ci_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ci_1     | 	at java.lang.Thread.run(Thread.java:748)
ci_1     | Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching updates.jenkins.io found.
ci_1     | 	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:214)
ci_1     | 	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
ci_1     | 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
ci_1     | 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
ci_1     | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
ci_1     | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
ci_1     | 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
ci_1     | 	... 29 more
ci_1     | 
ci_1     | Sep 17, 2018 1:56:48 PM jenkins.InitReactorRunner$1 onAttained
ci_1     | INFO: Completed initialization
ci_1     | Sep 17, 2018 1:56:48 PM hudson.WebAppMain$3 run
ci_1     | INFO: Jenkins is fully up and running
ci_1     | --> setting agent port for jnlp
ci_1     | --> setting agent port for jnlp... done
```

Docker Compose configuration:
```
  ci:
    build:
      context: ./server/jenkins
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    volumes:
      - ci:/var/jenkins_home
      - web_conf:/usr/src/conf:ro
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - JAVA_OPTS=-Djsse.enableSNIExtension=false -Dhttp.proxyHost=${proxy_host} -Dhttp.proxyPort=${proxy_port} -Dhttps.proxyHost=${proxy_host} -Dhttps.proxyPort=${proxy_port}
      - TZ=US/Pacific
      - JENKINS_OPTS=--prefix=/jenkins
    restart: unless-stopped
```

The `Dockerfile` used likes like this:
```
FROM jenkins/jenkins:2.121.3-alpine

USER root

RUN apk add --update-cache                              \
      ...
    && rm -rf /var/cache/apk/*

USER jenkins
```

### Output of `docker version`

```bash
> docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

> docker-compose --version
docker-compose version 1.22.0, build f46880f
```

### Other relevant information

```bash
> nslookup 
> updates.jenkins.io
...
Non-authoritative answer:
updates.jenkins.io	canonical name = mirrors.jenkins.io.
Name:	mirrors.jenkins.io
Address: 52.202.51.185
``` 
It seems that Jenkins tries to access `updates.jenkins.io` but that seems to match `mirrors.jenkins.io`, if this makes sense...

**Comment by rvernica** [comment]
I removed the `JAVA_OPTS` line from Docker Compose configuration file and it works fine. The web proxy was not needed in this instance. Sorry for the trouble.
