### ISSUE TITLE
Inability to use install-plugins.sh file with minimum version as opposed to latest

### ISSUE THREAD

**Issue by jlestrada** [jenkinsci/docker#735]
I have a use case in which my remote nodes will be unable to upgrade to Java 8 which is required with the latest versions of Jenkins. However, I am able to specify an older version of Jenkins within my Dockerfile (2.46.3) which works great! 

The issue that comes into play is the ability to download compatible plugins, more specifically the dependencies of the plugins. Using the install-plugins.sh file I can write out which plugins i need as well as the versions that fit the for the older Jenkins version (again 2.46.3). 

Issues come up when the dependencies of those plugins are required, the current iteration of the script file defaults to latest installs for the respective plugin. This breaks the running Jenkins instance because it is not the latest. 

Right now, I am attempting to monkey around with the install-plugins.sh file to get it to download the minimum version. I can see a previous iteration of the file actually defaulted to min version install only. The issue I am seeing with that is it will not overwrite a previously installed plugin (example script-security:1.16 to script-security:1.18).

I am awful at shell script writing so if anyone has a similar use case with solution it is greatly appreciated. 

In regards to the bug being filed, there should be an ability to easily revert from "latest" to "Minimum" for plugin installs. I can see a need for this as Jenkins continues to evolve and reasons for older versions are needed.

**Comment by jlestrada** [comment]
In order to repeat the issue users can write out a Dockerfile with the below content.

```
FROM jenkins:2.46.3
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt 
```

and add in plugins.txt

`workflow-aggregator:2.0`

When issuing a `docker run "jenkins-built-image"` the output will note an ability to load the plugin as shown below.

> SEVERE: Failed Loading plugin Structs Plugin v1.17 (structs)
> java.io.IOException: Structs Plugin v1.17 failed to load.
>  - You must update Jenkins from v2.46.3 to v2.60.3 or later to run this plugin.
> 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
> 	at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
> 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
> 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
> 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1089)
> 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
> 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Oct 08, 2018 4:54:58 PM jenkins.InitReactorRunner$1 onTaskFailed
> SEVERE: Failed Loading plugin Pipeline: Step API v2.16 (workflow-step-api)
> java.io.IOException: Pipeline: Step API v2.16 failed to load.
>  - Structs Plugin v1.17 failed to load. Fix this plugin first.
> 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
> 	at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
> 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
> 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
> 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1089)
> 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
> 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Oct 08, 2018 4:54:58 PM jenkins.InitReactorRunner$1 onTaskFailed
> SEVERE: Failed Loading plugin SCM API Plugin v2.2.8 (scm-api)
> java.io.IOException: SCM API Plugin v2.2.8 failed to load.
>  - Structs Plugin v1.17 failed to load. Fix this plugin first.
> 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
> 	at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
> 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
> 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
> 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1089)
> 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
> 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
