### ISSUE TITLE
Some plugins failed to install properly, you may retry installing them or continue with the failed plugins

### ISSUE THREAD

**Issue by Joon-S** [jenkinsci/docker#779]
I did it in https://hub.docker.com/_/jenkins
But plugins issues break out after installing plugins
I didn't do nothing at all 
thank you and sorry for my poor English

### Docker commands that you execute
`docker run -d -p 8100:8080 -p 8200:50000 jenkins`

### Actual result
in docker logs

Dec 24, 2018 8:03:10 AM hudson.model.UpdateCenter$DownloadJob run
SEVERE: Failed to install Pipeline: Stage View
java.io.IOException: Failed to dynamically deploy this plugin
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1893)
        at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to install pipeline-stage-view plugin
        at hudson.PluginManager.dynamicLoad(PluginManager.java:874)
        at hudson.PluginManager.dynamicLoad(PluginManager.java:813)
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1889)
        ... 5 more
Caused by: java.io.IOException: Pipeline: Stage View Plugin v2.10 failed to load.
 - Pipeline: REST API Plugin v2.10 failed to load. Fix this plugin first.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager.dynamicLoad(PluginManager.java:864)
        ... 7 more

### Output of `docker version`

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by carlossg** [comment]
Thats not the latest image use Jenkins/Jenkins

**Comment by rafaelmonteiroarj** [comment]
@carlossg  Obrigado!

**Comment by sbhr574** [comment]
I am also facing same problem how to resolve this. !!

**Comment by paramsinghvc** [comment]
There no such Docker image as `Jenkins/Jenkins`. It's `jenkins/jenkins`.

**Comment by nanakwafo** [comment]
faced the same issue 
use     docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins

**Comment by JoeyJGarcia** [comment]
Using use docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins

vs

use docker run -p 8080:8080 -p 50000:50000 jenkins

Worked for me.  Of course, I did a docker pull of jenkins/jenkins first

**Comment by yellowstone-bbc** [comment]
Faced the same issue and tried the below command to run a new Image of Jenkins in Docker. This resolved the issue.

**Command :** docker container run -p 8090:8080 jenkins/jenkins

**Comment by vegatech** [comment]
i was facing this error and solved including "future-java"  on my jenkins.xml set on the tag <arguments>,  after  "-jar" parameter as bellow:  -jar "d:\Jenkins\jenkins.war" --enable-future-java flag --httpPort=8089  --webroot="d:\Jenkins\war" --pluginroot="d:\Jenkins\plugins
