### ISSUE TITLE
How to set the requestHeaderSize?

### ISSUE THREAD

**Issue by TheDukeDK** [jenkinsci/docker#842]
### Docker commands that you execute
Starting a container and passing in `JENKINS_OPTS="--httpPort=8083 --requestHeaderSize=32768"` as I need to increase the header size supported by jetty.

### Actual result
It doesn't seem like we can pass more than one parameter to JENKINS_OPTS?
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2019-06-21 07:26:08.955+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @608ms to org.eclipse.jetty.util.log.JavaUtilLog
2019-06-21 07:26:09.116+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2019-06-21 07:26:09.155+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2019-06-21 07:26:09.207+0000 [id=1]     INFO    winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to start a listener: winstone.HttpConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:217)
        at winstone.Launcher.<init>(Launcher.java:175)
        at winstone.Launcher.main(Launcher.java:362)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:375)
        at Main.main(Main.java:151)
Caused by: java.lang.NumberFormatException: For input string: "8083 --requestHeaderSize=32768"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at winstone.cmdline.Option.intArg(Option.java:307)
        at winstone.cmdline.Option$OInt.get(Option.java:219)
        at winstone.HttpConnectorFactory.start(HttpConnectorFactory.java:30)
        at winstone.Launcher.spawnListener(Launcher.java:215)
        ... 8 more
2019-06-21 07:26:09.209+0000 [id=1]     SEVERE  winstone.Logger#logInternal: Container startup failed
java.lang.NumberFormatException: For input string: "8083 --requestHeaderSize=32768"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at winstone.cmdline.Option.intArg(Option.java:307)
        at winstone.cmdline.Option$OInt.get(Option.java:219)
        at winstone.HttpConnectorFactory.start(HttpConnectorFactory.java:30)
        at winstone.Launcher.spawnListener(Launcher.java:215)
Caused: java.io.IOException: Failed to start a listener: winstone.HttpConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:217)
        at winstone.Launcher.<init>(Launcher.java:175)
        at winstone.Launcher.main(Launcher.java:362)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:375)
        at Main.main(Main.java:151)
```

### Expected outcome
Jenkins is started and jetty can handle headers greater than 8k.

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No.

### Output of `docker version`
```Docker version 17.12.0-ce, build c97c6d6```

**Comment by slide** [comment]
Which image are you using?

**Comment by galek** [comment]
is actual
277.2 (jenkins/jenkins:lts) and some problem with 288.2 (jenkins/jenkins:latest)

**Comment by slide** [comment]
@galek Can you show the invocation of docker you are using?

**Comment by galek** [comment]
@slide , yep, but I'm using portainer (visual interface for managing containers)
I can show settings 
![image](https://user-images.githubusercontent.com/7027840/114801460-66cf6f80-9da4-11eb-92bf-be76bd928650.png)
![image](https://user-images.githubusercontent.com/7027840/114801503-78187c00-9da4-11eb-9e47-3489b6e9e744.png)
![image](https://user-images.githubusercontent.com/7027840/114801512-81a1e400-9da4-11eb-8512-9512f63c728e.png)
![image](https://user-images.githubusercontent.com/7027840/114801546-91b9c380-9da4-11eb-98f5-7a0b51d1d797.png)

**Comment by slide** [comment]
I don't see the JENKINS_OPTS in there (I could be blind...). Is there a way to see what command portainer will generate?

**Comment by galek** [comment]
@slide , hello
Now is not actual. Sorry for the long time reply. 
This was an erroneous update of all plugins and the major Jenkins version

**Comment by slide** [comment]
So, there is no issue? Can we close this then?

**Comment by galek** [comment]
@slide , for me - yes, it's not actual.
