### ISSUE TITLE
How to pass slaveAgentPort as JENKINS_OPTS inside Dockerfile

### ISSUE THREAD

**Issue by shashank-k** [jenkinsci/docker#882]
I have this line in Dockerfile

`ENV JENKINS_OPTS --httpPort=9030 -jenkins.model.Jenkins.slaveAgentPort=-1`

I am getting the following error after I run it. 

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:375)
        at Main.main(Main.java:151)
Caused by: java.lang.IllegalArgumentException: Unrecognized option: --jenkins.model.Jenkins.slaveAgentPort=-1
        at winstone.cmdline.CmdLineParser.parse(CmdLineParser.java:52)
        at winstone.Launcher.getArgsFromCommandLine(Launcher.java:363)
```

# How I run this

```
docker run --net=host -d -v /jenkins_1/jenkins:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins:1.0
```

Note: I have a requirement to use host network. 

# What is required

**Just to reiterate, passing ENV (similar to `--env JENKINS_SLAVE_AGENT_PORT=50001`) does not work and only option I am left is to pass it as `JENKINS_OPTS`** 

I have to either disable the slaveAgentPort or assign a different port to slaveAgentPort. 

Any help is really appriciated.

**Comment by dispalt** [comment]
try passing as this:
```
-Djenkins.model.Jenkins.slaveAgentPort
```
