### ISSUE TITLE
install-plugins.sh and jenkins-support scripts ignore implied dependencies copied from WAR

### ISSUE THREAD

**Issue by suranc** [jenkinsci/docker#923]
# Problem Description

## What I see happening

The `install-plugins.sh` script will download all explicitly requested plugin versions.  It will also resolves any transitive dependencies to a "latest-available" list of additional plugins to download, all of which are downloaded to a staging area.

The `copy_reference_file()` function in `jenkins-support` will copy these plugin files from the staging area to `/var/jenkins_home/plugins` to create a set of desired plugins and dependency plugins.  Anything copied is tagged with a `.version_from_image` marker to indicate they are script-managed, however any plugins already present without this marker and the copy is skipped. Upon start of the Jenkins WAR any still unresolved implied "detached" dependencies will then also be installed to `/var/jenkins_home/plugins`, but without a `.version_from_image` marker.

## Where it causes issues

This works initially to create an N set of plugin files that will start and work together.  However, when one of the dependency plugins (brought in as latest available version) is updated and the new version being updated to explicitly requires a newer version of a previously-implied "detached" dependency, the newly required version is skipped. 

This leads to an "N+1" set of plugin files that will fail to start together, because a now-explicitly required dependency is not present.  That's since the `copy_reference_file()` function skipped copying this dependency to `/var/jenkins_home/plugins` since the initial implicitly-implied version is already present without the `.version_from_image` marker.

# Background

I am using this image primarily with the helm/stable/jenkins helm chart, which relies on this set of scripts to install plugins as defined in a list in the values file.  Sticking to the paradigm of strictly managing our set of plugins through the `master.installPlugins` section has overall worked very well.  We have several areas managing servers using this pattern.

However, we've run into a reoccurring situation where plugins will fail to run because of unresolved dependencies where the version present is too old.  This is especially problematic for things like the kubernetes plugin, where it stores its settings in the config.xml and its absence erases that config section from this file.  

It does not seem to take a plugin update in the values or some other user action to trigger this.  Pod evictions or otherwise will cause a rescheduling and reflow of the entire pod lifecycle, which leads to plugin dependency updates being skipped and the above problem.

# To Recreate

While it was difficult to recreate the exact scenario that led to the issues, I've been able to create a set of steps to recreate a set of files that hit the exact version mismatch we encountered. 

* Do a helm install of stable/jenkins which has persistence as well as these values:
    ```
    master:
    image: "jenkins/jenkins"
    imageTag: "2.197-alpine"
    installPlugins:
        - kubernetes:1.19.2
    ```
* Exec into the master pod, and run `cd /var/jenkins_home/plugins; rm -rf bouncycastle-api*; wget https://updates.jenkins-ci.org/download/plugins/bouncycastle-api/2.16.0/bouncycastle-api.hpi`
* Delete the master pod.

Upon start of the new pod, the kubernetes plugin will fail to start because of the missing minimum 2.17 required `bouncycastle-api` dependency.  

# Potential Resolution

From my testing, I was able to work around this by adding this value to my helm values file:
```
master:
  containerEnv:
    - name: TRY_UPGRADE_IF_NO_MARKER
      value: "true"
```

I debated sending a PR to the helm chart which would set `TRY_UPGRADE_IF_NO_MARKER` to "true" if there was a `installPlugins` section present.  However, that really feels like a dodge around what seems to be ultimately a lack of marking script-managed dependencies with their respective `.from_image_version` tag.  It also seems like making too great of an assumption about how an user may want to manage their plugins.  

Another alternative I think might more fundamentally solve the problem would be to make [this](https://github.com/jenkinsci/docker/blob/a7401da3c53b9cbc7d5e4c8a8a4eba32acd3712a/install-plugins.sh#L169) section of `install-plugins.sh` not skip "detached-plugins".  However, while many of those seem to inevitably get brought in anyways by most plugins, many others like the `cvs` plugin will be much less commonly desired.  

Probably the closest to a true "fix" I can think of would be to apply the same implied dependency logic the WAR uses in the `install-plugins.sh` script based on the jenkins version dependency.

**Comment by bassplay3r** [comment]
kt logs rude-maltese-jenkins-85b7886b49-grtmp jenkins
[/var/jenkins_home/plugins/workflow-api.jpi]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
[/usr/share/jenkins/ref/plugins/workflow-api.jpi]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-01-24 16:02:47.023+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @407ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-01-24 16:02:47.156+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2020-01-24 16:02:47.209+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-01-24 16:02:47.278+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.z-SNAPSHOT; built: 2019-05-02T00:04:53.875Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_232-b09
2020-01-24 16:02:47.712+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-01-24 16:02:47.773+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-01-24 16:02:47.774+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-01-24 16:02:47.777+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2020-01-24 16:02:48.197+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-01-24 16:02:48.332+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@798162bc{Jenkins v2.204.1,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2020-01-24 16:02:48.351+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@64616ca2{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-01-24 16:02:48.351+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @1735ms
2020-01-24 16:02:48.352+0000 [id=21]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine v4.0 running: controlPort=disabled
2020-01-24 16:02:49.850+0000 [id=27]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-01-24 16:02:50.695+0000 [id=31]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Inspecting plugin /var/jenkins_home/plugins/workflow-api.jpi
java.util.zip.ZipException: archive is not a ZIP archive
        at org.apache.tools.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:777)
        at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:713)
        at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:458)
        at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:216)
        at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:188)
Caused: Error while expanding /var/jenkins_home/plugins/workflow-api.jpi

**Comment by RomanSaveljev** [comment]
I faced the same issue and finally decided not to mix two ways of managing plugins. Installation from ref is applied only on the first bootstrap, then it will be skipped and users can change the plugins through UI or otherwise.

**Comment by suranc** [comment]
@RomanSaveljev I've actually taken the opposite approach and had some success.  We manage our plugins strictly through the `values.yaml` in the helm chart, and instruct users not to modify plugins through the interface.  

Right now our server uses pinned versions of the Jenkins master and the plugins, but we've limited the plugins listed to only the highest level plugins and removed any pulled in as dependencies from the `values.yaml`.  That has helped reduce getting into a pickle where a newer transitive dependency requires a higher version of dependency plugin than the version that gets pinned.  While it has not fully eliminated the issue, it does seem to have minimized it to a rare occurrence.

A future plan for when we get around to it would be to go in one of two directions, that being to go even higher level in what we specify or to go more granular and specify everything.  The two options being:

* Do not specify versions on plugins or the Jenkins master, and only specify high level plugins needed without specifying any dependencies. - Any server restart results in an update, but with the version set being determined at fresh to latest each time.
* Explicitly list all plugins, and their versions along with pinning the Jenkins container to a specific version.  - The stack of plugins will stay static across server restarts.

**Comment by timja** [comment]
install-plugins.sh is deprecated for removal, the Jenkins helm chart no longer uses it
